### ISSUE TITLE
[Bug report] - No ephys error

### ISSUE THREAD

**Issue by rossant** [int-brain-lab/iblenv#100]
https://alyx.internationalbrainlab.org/admin/jobs/task/a2c7822c-31c3-454b-a023-b62aab546dfe/change/

```
2020-11-06 18:24:13,484,484 INFO [tasks.py:68] Starting job <class 'ibllib.pipes.ephys_preprocessing.EphysTrials'>
2020-11-06 18:24:13,490,490 ERROR [tasks.py:76] Traceback (most recent call last):
File "/home/experiment/Documents/PYTHON/envs/iblenv/lib/python3.6/site-packages/ibllib/pipes/tasks.py", line 72, in run
self.outputs = self._run(**kwargs)
File "/home/experiment/Documents/PYTHON/envs/iblenv/lib/python3.6/site-packages/ibllib/pipes/ephys_preprocessing.py", line 172, in _run
dsets, out_files = ephys_fpga.extract_all(self.session_path, save=True)
File "/home/experiment/Documents/PYTHON/envs/iblenv/lib/python3.6/site-packages/ibllib/io/extractors/ephys_fpga.py", line 656, in extract_all
sync, chmap = _get_main_probe_sync(session_path, bin_exists=bin_exists)
File "/home/experiment/Documents/PYTHON/envs/iblenv/lib/python3.6/site-packages/ibllib/io/extractors/ephys_fpga.py", line 501, in _get_main_probe_sync
raise FileNotFoundError(f"No ephys files found in {session_path}")
FileNotFoundError: No ephys files found in /mnt/s0/Data/Subjects/KS040/2020-11-06/001

2020-11-06 18:24:13,490,490 INFO [tasks.py:77] Job <class 'ibllib.pipes.ephys_preprocessing.EphysTrials'> errored
2020-11-06 18:24:13,491,491 INFO [tasks.py:87] N outputs: 0
2020-11-06 18:24:13,491,491 INFO [tasks.py:88] --- 0.0061337947845458984 seconds run-time ---
```

**Comment by GaelleChapuis** [comment]
@karolinasocha could you please check that this is indeed an important session and that the data is missing unexpectedly?

**Comment by karolinasocha** [comment]
no, this is a session from my individual project.
