### ISSUE TITLE
[Bug report] - phy_launcher.py  error

### ISSUE THREAD

**Issue by ibldan** [int-brain-lab/iblenv#13]
**Describe the bug**
trying to run the phy launcher, I'm getting an error below.    git pull for all folders,  already follow this instruction (https://github.com/int-brain-lab/iblenv)  to update my environment to install new packages.

**Screenshots**
Traceback (most recent call last):
  File "phy_launcher.py", line 8, in <module>
    from oneibl.one import ONE
  File "C:\Users\Julia Desk\int-brain-lab\ibllib-repo\oneibl\one.py", line 13, in <module>
    import oneibl.webclient as wc
  File "C:\Users\Julia Desk\int-brain-lab\ibllib-repo\oneibl\webclient.py", line 13, in <module>
    from alf.io import is_uuid_string
  File "C:\Users\Julia Desk\int-brain-lab\ibllib-repo\alf\io.py", line 20, in <module>
    from brainbox.io import parquet
  File "C:\Users\Julia Desk\int-brain-lab\ibllib-repo\brainbox\io\parquet.py", line 4, in <module>
    from numba import jit
ModuleNotFoundError: No module named 'numba'

**Comment by oliche** [comment]
It seems the numba package is not installed on your computer.

The conda environment has been updated recently, so it needs a refresh, in a terminal,
- cd to the iblenv repository
- activate the environment
- update it: `conda env update --file iblenv.yaml --prune`

Then restart the Python console / IDE.
Let us know if it still shows this error.

**Comment by ibldan** [comment]
get the new error below after update iblenv: 

**
Traceback (most recent call last):
  File "phy_launcher.py", line 100, in <module>
    launch_phy(str(args.probe_label), eid=str(args.eid))
  File "phy_launcher.py", line 73, in launch_phy
    plugin_dirs=[Path(__file__).resolve().parent])
  File "C:\Users\Julia Desk\int-brain-lab\phy\phy\apps\base.py", line 467, in __init__
    super(TemplateMixin, self).__init__(*args, **kwargs)
  File "C:\Users\Julia Desk\int-brain-lab\phy\phy\apps\base.py", line 878, in __init__
    self.model = self._create_model(dir_path=dir_path, **kwargs) if model is None else model
  File "C:\Users\Julia Desk\int-brain-lab\phy\phy\apps\template\gui.py", line 92, in _create_model
    return TemplateModel(dir_path=dir_path, **kwargs)
  File "C:\Users\Julia Desk\int-brain-lab\phylib\phylib\io\model.py", line 261, in __init__
    self._load_data()
  File "C:\Users\Julia Desk\int-brain-lab\phylib\phylib\io\model.py", line 270, in _load_data
    self.spike_samples, self.spike_times = self._load_spike_samples()
  File "C:\Users\Julia Desk\int-brain-lab\phylib\phylib\io\model.py", line 562, in _load_spike_samples
    times = self._read_array(times_path)
  File "C:\Users\Julia Desk\int-brain-lab\phylib\phylib\io\model.py", line 397, in _read_array
    raise IOError()
OSError
**

**Comment by oliche** [comment]
Ok that's a whole different issue.

Can you give us a bit more context ? What session are you trying to load ?
There is an issue when trying to load the sample waveforms for this session.

**Comment by ibldan** [comment]
I delete iblenv, and reinstall all. then get this error below:

**
(iblenv) C:\Users\Julia Desk\int-brain-lab\iblapps\launch_phy>python phy_launcher.py -e e535fb62-e245-4a48-b119-88ce62a6fe67  -p probe01
Traceback (most recent call last):
  File "phy_launcher.py", line 5, in <module>
    from phy.apps.template import TemplateController, template_gui
ModuleNotFoundError: No module named 'phy'
**

**Comment by ibldan** [comment]
See new error below when I try it again (about this session:      e535fb62-e245-4a48-b119-88ce62a6fe67 probe01 ; 2020-06-09T07:59:14.315700 ; DY_013 ; ): 

**
(iblenv) C:\Users\Julia Desk\int-brain-lab\iblapps\launch_phy>python phy_launcher.py -e e535fb62-e245-4a48-b119-88ce62a6fe67  -p probe01
Traceback (most recent call last):
  File "phy_launcher.py", line 5, in <module>
    from phy.apps.template import TemplateController, template_gui
  File "C:\Users\Julia Desk\int-brain-lab\phy\phy\apps\__init__.py", line 25, in <module>
    from .base import (  # noqa
  File "C:\Users\Julia Desk\int-brain-lab\phy\phy\apps\base.py", line 21, in <module>
    from phylib.io.array import SpikeSelector, _flatten
ImportError: cannot import name 'SpikeSelector' from 'phylib.io.array' (C:\Users\Julia Desk\.conda\envs\iblenv\lib\site-packages\phylib\io\array.py)
**

**Comment by ibldan** [comment]
if I try to do *pip uninstall phylib* , and then get this error:
**
(iblenv) C:\Users\Julia Desk\int-brain-lab\iblapps\launch_phy>python phy_launcher.py -e e535fb62-e245-4a48-b119-88ce62a6fe67  -p probe01
Traceback (most recent call last):
  File "phy_launcher.py", line 8, in <module>
    from oneibl.one import ONE
  File "C:\Users\Julia Desk\.conda\envs\iblenv\lib\site-packages\oneibl\one.py", line 18, in <module>
    from oneibl.dataclass import SessionDataInfo
  File "C:\Users\Julia Desk\.conda\envs\iblenv\lib\site-packages\oneibl\dataclass.py", line 5, in <module>
    from brainbox.io import parquet
  File "C:\Users\Julia Desk\.conda\envs\iblenv\lib\site-packages\brainbox\io\parquet.py", line 5, in <module>
    import pyarrow.parquet as pq
  File "C:\Users\Julia Desk\.conda\envs\iblenv\lib\site-packages\pyarrow\__init__.py", line 49, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: DLL load failed: The specified procedure could not be found.
**

**Comment by ibldan** [comment]
try to load another session (KS023, 2019-12-10, probe01 aad23144-0e52-4eac-80c5-c4ee2decb198),  got this error below: 

**
(iblenv) C:\Users\Julia Desk\int-brain-lab\iblapps\launch_phy>python phy_launcher.py -e aad23144-0e52-4eac-80c5-c4ee2decb198  -p probe00
Connected to https://alyx.internationalbrainlab.org as feihu
Traceback (most recent call last):
  File "phy_launcher.py", line 100, in <module>
    launch_phy(str(args.probe_label), eid=str(args.eid))
  File "phy_launcher.py", line 73, in launch_phy
    plugin_dirs=[Path(__file__).resolve().parent])
  File "C:\Users\Julia Desk\int-brain-lab\phy\phy\apps\base.py", line 467, in __init__
    super(TemplateMixin, self).__init__(*args, **kwargs)
  File "C:\Users\Julia Desk\int-brain-lab\phy\phy\apps\base.py", line 872, in __init__
    assert self.dir_path.exists()
AssertionError
**

**Comment by mayofaulkner** [comment]
Solved by pulling latest changes on develop branch of iblapps 
```
cd iblapps
git checkout develop
git pull
```
