### ISSUE TITLE
[Bug report] - Corrupted camera file on FI?

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#142]
**Describe the bug**
I cannot seem to be able to open
"http://[REDACTED]@ibl.flatironinstitute.org/hoferlab/Subjects/SWC_061/2020-11-27/001/raw_video_data/_iblrig_leftCamera.raw.3d693de7-2d91-4793-9bab-50f4545a5380.mp4"

either manually (clicking from the link) or with the video streamer (getting this error below)
```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fb165536000] moov atom not found
OpenCV: Couldn't read video stream from file "http://[REDACTED]@ibl.flatironinstitute.org/hoferlab/Subjects/SWC_061/2020-11-27/001/raw_video_data/_iblrig_leftCamera.raw.3d693de7-2d91-4793-9bab-50f4545a5380.mp4"
Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-6618503430b5>", line 70, in <module>
    axs[i_cam].imshow(im, cmap='gray', vmin=0, vmax=255)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.7/site-packages/matplotlib/__init__.py", line 1565, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 5626, in imshow
    im.set_data(X)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.7/site-packages/matplotlib/image.py", line 694, in set_data
    "float".format(self._A.dtype))
TypeError: Image data of dtype object cannot be converted to float
```

I am not sure how to address this ? Is this file corrupted somehow (how to check)?

**To Reproduce**
Click on the link above

**Comment by k1o0** [comment]
I suggest downloading the video and seeing whether you can open it locally

**Comment by GaelleChapuis** [comment]
I tried downloading and opening with my regular mp4 reader, and I cannot (screenshot attached).
It does look to me that this file is corrupted.
<img width="405" alt="Capture d’écran 2020-12-15 à 11 47 27" src="https://user-images.githubusercontent.com/43007596/102205374-65ac3580-3ecb-11eb-8942-84be3e21e9f8.png">

**Comment by k1o0** [comment]
I've seen this as well.  I'm no expert but I would assume the video is lost for good.  I will add something to the QC so that these sessions are marked as critical.

**Comment by GaelleChapuis** [comment]
This session was marked as critical by the user, so closing this issue, but a QC to catch this sounds great indeed.
