### ISSUE TITLE
[Bug report] - passive extraction fails

### ISSUE THREAD

**Issue by rossant** [int-brain-lab/iblenv#156]
https://alyx.internationalbrainlab.org/admin/jobs/task/42520b83-75a1-4804-8dd3-dbbfc2150ff0/change/

```
2020-12-31 13:53:51,518,518 INFO [tasks.py:68] Starting job <class 'ibllib.pipes.ephys_preprocessing.EphysPassive'>
2020-12-31 13:53:52,084,84 ERROR [ephys_passive.py:528] Failed to extract passive periods: [Errno 2] No such file or directory: '/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.8/site-packages/ibllib/io/extractors/ephys_sessions/passive_stim_meta.json'
2020-12-31 13:53:52,084,84 ERROR [tasks.py:76] Traceback (most recent call last):
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.8/site-packages/ibllib/pipes/tasks.py", line 73, in run
self.outputs = self._run(**kwargs)
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.8/site-packages/ibllib/pipes/ephys_preprocessing.py", line 403, in _run
data, paths = ephys_passive.PassiveChoiceWorld(self.session_path).extract(save=True)
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.8/site-packages/ibllib/io/extractors/base.py", line 39, in extract
files = self._save(out, path_out=path_out) if save else None
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.8/site-packages/ibllib/io/extractors/base.py", line 78, in _save
_write_to_disk(fpath, data)
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.8/site-packages/ibllib/io/extractors/base.py", line 65, in _write_to_disk
data.to_csv(file_path, sep=sep)
AttributeError: 'NoneType' object has no attribute 'to_csv'
```

**Comment by nbonacchi** [comment]
Weird, passive extraction failed because it did not find a doc that should be in the pregenerated sessions folder...
ibllib 1.5.32 should have the file, maybe it's not in the MANIFEST.in; still, this would only be a problem if ibllib was isnatlled from PyPI. Local servers are running on latest master repo installed as `pip install -e . ` and updated daily and not from PyPI 
Is this a CI run?

**Comment by nbonacchi** [comment]
Also probably the base extractor should not fail if the data is None jsut not save anything and throw a warning. What do you think @rossant ?

**Comment by rossant** [comment]
> Also probably the base extractor should not fail if the data is None jsut not save anything and throw a warning. What do you think @rossant ?

absolutely, whatever the cause, there should ideally be a clearer error message/warning

**Comment by rossant** [comment]
this is from angelakilab
7a589a03/CSP013/2020-09-29/001

**Comment by mayofaulkner** [comment]
Looks like was an error from no passive data existing. Closing this issue for now.
