### ISSUE TITLE
[Bug report] - Cannot connect to DJ using Phy launcher

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#159]
**Describe the bug**
I cannot launch the phy launcher due to seemingly problem with DJ connection.

**To Reproduce**
Using latest iblapps develop branch.
Launch from terminal:
```
python /Users/gaelle/Documents/Git/int-brain-lab/iblapps/launch_phy/phy_launcher.py -e 89f0d6ff-69f4-45bc-b89e-72868abb042a -p probe00
```
from within the corresponding folder:
```
(iblenv) macbook-pro-de-gaelle:alf gaelle$ pwd
/Users/gaelle/Downloads/FlatIron/churchlandlab/Subjects/CSHL047/2020-01-20/001/alf

```
The launcher seems to work fine (downloads data etc) until I have to input my DJ credentials.
When I do so, I get a first error:

```
16:18:41.917 [E] plugin:111           (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")
Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/pymysql/connections.py", line 569, in connect
    sock = socket.create_connection(
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/phy/utils/plugin.py", line 109, in discover_plugins
    mod = imp.load_module(modname, file, path, descr)  # noqa
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/gaelle/Documents/Git/int-brain-lab/iblapps/launch_phy/populate_cluster_table.py", line 1, in <module>
    from launch_phy import cluster_table
  File "/Users/gaelle/Documents/Git/int-brain-lab/iblapps/launch_phy/cluster_table.py", line 2, in <module>
    from ibl_pipeline import reference
  File "/Users/gaelle/Documents/Git/int-brain-lab/IBL-pipeline/ibl_pipeline/__init__.py", line 12, in <module>
    schema = dj.schema('ibl_storage')
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/datajoint/schemas.py", line 71, in __init__
    self.activate(schema_name)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/datajoint/schemas.py", line 95, in activate
    self.connection = conn()
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/datajoint/connection.py", line 94, in conn
    conn.connection = Connection(host, user, password, None, init_fun, use_tls)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/datajoint/connection.py", line 146, in __init__
    self.connect()
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/datajoint/connection.py", line 169, in connect
    self._conn = client.connect(
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/pymysql/connections.py", line 327, in __init__
    self.connect()
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/pymysql/connections.py", line 619, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")
16:18:41.966 [D] plugin:78            Found plugin module `cluster_table.py`.
```
after which I am prompted to enter my DJ credentials again.
After doing so again, I get this new error, and the launcher crashed (which comes back to the terminal command):
```
Please enter DataJoint username: [redacted]
Please enter DataJoint password: 
Connecting [redacted]@localhost:3306
16:19:01.365 [E] plugin:111           (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")
Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/pymysql/connections.py", line 569, in connect
    sock = socket.create_connection(
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/phy/utils/plugin.py", line 109, in discover_plugins
    mod = imp.load_module(modname, file, path, descr)  # noqa
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/gaelle/Documents/Git/int-brain-lab/iblapps/launch_phy/cluster_table.py", line 2, in <module>
    from ibl_pipeline import reference
  File "/Users/gaelle/Documents/Git/int-brain-lab/IBL-pipeline/ibl_pipeline/__init__.py", line 12, in <module>
    schema = dj.schema('ibl_storage')
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/datajoint/schemas.py", line 71, in __init__
    self.activate(schema_name)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/datajoint/schemas.py", line 95, in activate
    self.connection = conn()
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/datajoint/connection.py", line 94, in conn
    conn.connection = Connection(host, user, password, None, init_fun, use_tls)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/datajoint/connection.py", line 146, in __init__
    self.connect()
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/datajoint/connection.py", line 169, in connect
    self._conn = client.connect(
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/pymysql/connections.py", line 327, in __init__
    self.connect()
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/pymysql/connections.py", line 619, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")
16:19:01.366 [D] plugin:78            Found plugin module `phy_plugin.py`.
16:19:01.372 [D] plugin:36            Register plugin `phy_plugin.IBLMetricsPlugin`.
16:19:01.372 [D] plugin:145           Loading 1 plugins.
16:19:01.373 [D] plugin:156           Attached plugin IBLMetricsPlugin.
16:19:01.381 [D] context:209          The file `/Users/gaelle/Downloads/FlatIron/churchlandlab/Subjects/CSHL047/2020-01-20/001/alf/probe00/.phy/new_cluster_id.pkl` doesn't exist.
16:19:01.706 [D] context:185          Save data to `/Users/gaelle/Downloads/FlatIron/churchlandlab/Subjects/CSHL047/2020-01-20/001/alf/probe00/.phy/spikes_per_cluster.pkl`.
16:19:01.849 [D] gui:463              Creating GUI.
16:19:02.252 [D] state:46             Load /Users/gaelle/.phy/TemplateGUI/state.json for GUIState.
Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/joblib/func_inspect.py", line 265, in filter_args
    arg_dict[arg_name] = arg_defaults[position]
IndexError: tuple index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gaelle/Documents/Git/int-brain-lab/iblapps/launch_phy/phy_launcher.py", line 100, in <module>
    launch_phy(str(args.probe_label), eid=str(args.eid))
  File "/Users/gaelle/Documents/Git/int-brain-lab/iblapps/launch_phy/phy_launcher.py", line 74, in launch_phy
    gui = controller.create_gui()
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/phy/apps/base.py", line 1638, in create_gui
    self.supervisor.attach(gui)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/phy/cluster/supervisor.py", line 941, in attach
    self._create_views(
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/phy/cluster/supervisor.py", line 760, in _create_views
    gui, data=self.cluster_info, columns=self.columns, sort=sort)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/phy/cluster/supervisor.py", line 916, in cluster_info
    return [self.get_cluster_info(cluster_id) for cluster_id in self.clustering.cluster_ids]
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/phy/cluster/supervisor.py", line 916, in <listcomp>
    return [self.get_cluster_info(cluster_id) for cluster_id in self.clustering.cluster_ids]
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/phy/cluster/supervisor.py", line 745, in get_cluster_info
    out[key] = func(cluster_id)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/phy/utils/context.py", line 154, in memcached
    out = f(*args, **kwargs)
  File "/Users/gaelle/Documents/Git/int-brain-lab/iblapps/launch_phy/phy_plugin.py", line 80, in mean_amp_true
    waveforms = controller._get_waveforms_with_n_spikes(cluster_id,
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/joblib/memory.py", line 591, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/joblib/memory.py", line 483, in _cached_call
    func_id, args_id = self._get_output_identifiers(*args, **kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/joblib/memory.py", line 620, in _get_output_identifiers
    argument_hash = self._get_argument_hash(*args, **kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/joblib/memory.py", line 614, in _get_argument_hash
    return hashing.hash(filter_args(self.func, self.ignore, args, kwargs),
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/joblib/func_inspect.py", line 268, in filter_args
    raise ValueError(
ValueError: Wrong number of arguments for _get_waveforms_with_n_spikes(self, cluster_id, n_spikes_waveforms, batch_size_waveforms, current_filter=None):
     _get_waveforms_with_n_spikes(<phy.apps.template.gui.TemplateController object at 0x7f96a10102e0>, 0, n_spikes_waveforms=100) was called.
```

**Comment by GaelleChapuis** [comment]
This seems like a general connection problem as I cannot connect to DJ either via the notebook nor via python imports (example below).
```
from ibl_pipeline import acquisition
Please enter DataJoint username: >? [redacted]
Warning: Password input may be echoed.
Please enter DataJoint password: >? [redacted]
Connecting [redacted]@datajoint.internationalbrainlab.org:3306
```

```
Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-4c86d4a3a224>", line 1, in <module>
    from ibl_pipeline import acquisition
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/gaelle/Documents/Git/int-brain-lab/IBL-pipeline/ibl_pipeline/acquisition.py", line 2, in <module>
    from . import subject
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/gaelle/Documents/Git/int-brain-lab/IBL-pipeline/ibl_pipeline/subject.py", line 2, in <module>
    from . import reference
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/gaelle/Documents/Git/int-brain-lab/IBL-pipeline/ibl_pipeline/reference.py", line 152, in <module>
    class ParentRegion(dj.Imported):
  File "/Users/gaelle/Documents/Git/int-brain-lab/IBL-pipeline/ibl_pipeline/reference.py", line 159, in ParentRegion
    (reference.BrainRegion & 'parent is not NULL').proj()
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/datajoint/user_tables.py", line 48, in __and__
    return cls() & arg
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/datajoint/expression.py", line 197, in __and__
    return self.restrict(restriction)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/datajoint/expression.py", line 171, in restrict
    raise DataJointError("Attribute `%s` is not found in query." % next(
datajoint.errors.DataJointError: Attribute `not` is not found in query.
```


from notebook:

```
Please enter DataJoint username: [redacted]
Please enter DataJoint password: ········
Connecting [redacted]@datajoint.internationalbrainlab.org:3306
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
<ipython-input-2-2ba0053b5bab> in <module>
      1 # Imports and initialisation
      2 
----> 3 from ibl_pipeline import acquisition
      4 from ibl_pipeline.analyses import behavior as behavior_analysis
      5 import numpy as np

/src/IBL-pipeline/ibl_pipeline/__init__.py in <module>
     10 
     11 if os.environ.get('MODE') != 'public':
---> 12     schema = dj.schema('ibl_storage')
     13 
     14     @schema

/opt/conda/lib/python3.6/site-packages/datajoint/schemas.py in __init__(self, schema_name, context, connection, create_schema, create_tables)
     54         """
     55         if connection is None:
---> 56             connection = conn()
     57         self._log = None
     58 

/opt/conda/lib/python3.6/site-packages/datajoint/connection.py in conn(host, user, password, init_fun, reset, use_tls)
     86         init_fun = init_fun if init_fun is not None else config['connection.init_function']
     87         use_tls = use_tls if use_tls is not None else config['database.use_tls']
---> 88         conn.connection = Connection(host, user, password, None, init_fun, use_tls)
     89     return conn.connection
     90 

/opt/conda/lib/python3.6/site-packages/datajoint/connection.py in __init__(self, host, user, password, port, init_fun, use_tls)
    119         print("Connecting {user}@{host}:{port}".format(**self.conn_info))
    120         self._conn = None
--> 121         self.connect()
    122         if self.is_connected:
    123             logger.info("Connected {user}@{host}:{port}".format(**self.conn_info))

/opt/conda/lib/python3.6/site-packages/datajoint/connection.py in connect(self)
    149                              "STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION",
    150                     charset=config['connection.charset'],
--> 151                     **{k: v for k, v in self.conn_info.items()
    152                        if k != 'ssl_input'})
    153             except client.err.InternalError:

/opt/conda/lib/python3.6/site-packages/pymysql/__init__.py in Connect(*args, **kwargs)
     92     """
     93     from .connections import Connection
---> 94     return Connection(*args, **kwargs)
     95 
     96 from . import connections as _orig_conn

/opt/conda/lib/python3.6/site-packages/pymysql/connections.py in __init__(self, host, user, password, database, port, unix_socket, charset, sql_mode, read_default_file, conv, use_unicode, client_flag, cursorclass, init_command, connect_timeout, ssl, read_default_group, compress, named_pipe, autocommit, db, passwd, local_infile, max_allowed_packet, defer_connect, auth_plugin_map, read_timeout, write_timeout, bind_address, binary_prefix, program_name, server_public_key)
    325             self._sock = None
    326         else:
--> 327             self.connect()
    328 
    329     def _create_ssl_ctx(self, sslp):

/opt/conda/lib/python3.6/site-packages/pymysql/connections.py in connect(self, sock)
    586 
    587             self._get_server_information()
--> 588             self._request_authentication()
    589 
    590             if self.sql_mode is not None:

/opt/conda/lib/python3.6/site-packages/pymysql/connections.py in _request_authentication(self)
    851 
    852         self.write_packet(data)
--> 853         auth_packet = self._read_packet()
    854 
    855         # if authentication method isn't accepted the first byte

/opt/conda/lib/python3.6/site-packages/pymysql/connections.py in _read_packet(self, packet_type)
    674             if self._result is not None and self._result.unbuffered_active is True:
    675                 self._result.unbuffered_active = False
--> 676             packet.raise_for_error()
    677         return packet
    678 

/opt/conda/lib/python3.6/site-packages/pymysql/protocol.py in raise_for_error(self)
    221         errno = self.read_uint16()
    222         if DEBUG: print("errno =", errno)
--> 223         err.raise_mysql_exception(self._data)
    224 
    225     def dump(self):

/opt/conda/lib/python3.6/site-packages/pymysql/err.py in raise_mysql_exception(data)
    105     if errorclass is None:
    106         errorclass = InternalError if errno < 1000 else OperationalError
--> 107     raise errorclass(errno, errval)

OperationalError: (1045, "Access denied for user '[redacted]'@'172.31.38.195' (using password: YES)")
```

**Comment by GaelleChapuis** [comment]
Following the setup scheme https://int-brain-lab.github.io/iblenv/dj_docs/dj_credentials.html, I did:
```
import datajoint as dj
dj.conn()
Please enter DataJoint username: >? [redacted]
Warning: Password input may be echoed.
Please enter DataJoint password: >? [redacted]
Connecting [redacted]@datajoint.internationalbrainlab.org:3306
Out[5]: DataJoint connection (connected) [redacted]@datajoint.internationalbrainlab.org:3306
dj.config.save_local()
```
This did **not** successfully save my password in dj.config. With the password out of the dj.config, I still have the errors above when trying to launch Phy or importing from ibl-pipeline (after being prompted for my DJ password).

@shenshan you wrote twice `'database.user'`, so I tried changing `dj.config['database.password']`. The dj.config is now fully populated with the correct information. When launching dj.conn(), it connects straight away.
im```
port datajoint as dj
dj.conn()
Out[4
```]: DataJoint connection (connected) gaelle.chapuis@datajoint.internationalbrainlab.org:3306
However when I launch the import
`from ibl_pipeline import acquisition`
I still get the same error:
```
Backend Qt5Agg is interactive backend. Turning interactive mode on.
Connecting gaelle.chapuis@datajoint.internationalbrainlab.org:3306
Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-4c86d4a3a224>", line 1, in <module>
    from ibl_pipeline import acquisition
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/gaelle/Documents/Git/int-brain-lab/IBL-pipeline/ibl_pipeline/acquisition.py", line 2, in <module>
    from . import subject
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/gaelle/Documents/Git/int-brain-lab/IBL-pipeline/ibl_pipeline/subject.py", line 2, in <module>
    from . import reference
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/gaelle/Documents/Git/int-brain-lab/IBL-pipeline/ibl_pipeline/reference.py", line 152, in <module>
    class ParentRegion(dj.Imported):
  File "/Users/gaelle/Documents/Git/int-brain-lab/IBL-pipeline/ibl_pipeline/reference.py", line 159, in ParentRegion
    (reference.BrainRegion & 'parent is not NULL').proj()
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/datajoint/user_tables.py", line 48, in __and__
    return cls() & arg
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/datajoint/expression.py", line 197, in __and__
    return self.restrict(restriction)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/datajoint/expression.py", line 171, in restrict
    raise DataJointError("Attribute `%s` is not found in query." % next(
datajoint.errors.DataJointError: Attribute `not` is not found in query.
```

**Comment by GaelleChapuis** [comment]
I was running a pre-release version of DJ.
Issue with Datajoint fixed by doing:

```
pip uninstall datajoint
pip install datajoint==0.12.7
```
