### ISSUE TITLE
[Usage question] - How to download an image from the Notes using one

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#163]
**Describe the question you have**
I am trying to download an image saved on Alyx in the notes, e.g.: 
```
notes = one.alyx.rest('notes', 'list', django=f"text__icontains,Camera images")
notes[0] :
{'id': 'd90dec89-38c3-4ea9-853c-9ebf5155702b',
 'user': 'Gaelle',
 'date_time': '2020-12-15T11:34:22.566440',
 'content_type': 'actions.session',
 'object_id': 'da188f2c-553c-4e04-879b-c9ea2d1b9a93',
 'text': 'Single-frame camera images (n=0 camera missing)',
 'image': 'https://alyx.internationalbrainlab.org/uploaded/2020/12/15/CSH_ZAD_011__2020-03-23__da188f2c-553c-4e04-879b-c9ea2d1b9a93.da188f2c-553c-4_0Dhfbtn.png'}
```
I tried the various `one.load, one.download[...]` commands to no avoid.
What would be the correct nomenclature?

**Is your question related to a specific product?**
ONE

**Comment by GaelleChapuis** [comment]
I had tried this for example :
```
img_test = one._download_file(target_dir = '/Users/gaelle/Downloads', url=notes[0]['image'])
2021-01-06 17:37:46.304 ERROR    [webclient.py:129] HTTP Error 403: Forbidden https://alyx.internationalbrainlab.org/uploaded/2020/12/15/CSH_ZAD_011__2020-03-23__da188f2c-553c-4e04-879b-c9ea2d1b9a93.da188f2c-553c-4_0Dhfbtn.png
Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-4a7c514028aa>", line 1, in <module>
    img_test = one._download_file(target_dir = '/Users/gaelle/Downloads', url=notes[0]['image'])
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/oneibl/one.py", line 793, in _download_file
    local_path, md5 = wc.http_download_file(
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/oneibl/webclient.py", line 130, in http_download_file
    raise e
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/oneibl/webclient.py", line 127, in http_download_file
    u = urllib.request.urlopen(req)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by rossant** [comment]
relevant? https://stackoverflow.com/a/13303773/1595060

**Comment by GaelleChapuis** [comment]
Huge thanks to @oliche , here is the new download function:
```
from oneibl.one import ONE
one = ONE()
url = 'https://alyx.internationalbrainlab.org/uploaded/2020/12/15/CSH_ZAD_011__2020-03-23__da188f2c-553c-4e04-879b-c9ea2d1b9a93.da188f2c-553c-4_0Dhfbtn.png'
fpath = one.alyx.download_file(url)
```
