### ISSUE TITLE
[Bug report] - Phy launcher bug on specific session

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#167]
**Describe the bug**
Error upon launching the phy launcher on specific session (see below), have not yet tried to reproduce on other session.

**To Reproduce**
Launch from terminal:
`python /Users/gaelle/Documents/Git/int-brain-lab/iblapps/launch_phy/phy_launcher.py -e 89f0d6ff-69f4-45bc-b89e-72868abb042a -p probe00`
from within the corresponding folder:
```
(iblenv) macbook-pro-de-gaelle:alf gaelle$ pwd
/Users/gaelle/Downloads/FlatIron/churchlandlab/Subjects/CSHL047/2020-01-20/001/alf
```
error:
```
Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/joblib/func_inspect.py", line 265, in filter_args
    arg_dict[arg_name] = arg_defaults[position]
IndexError: tuple index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gaelle/Documents/Git/int-brain-lab/iblapps/launch_phy/phy_launcher.py", line 100, in <module>
    launch_phy(str(args.probe_label), eid=str(args.eid))
  File "/Users/gaelle/Documents/Git/int-brain-lab/iblapps/launch_phy/phy_launcher.py", line 74, in launch_phy
    gui = controller.create_gui()
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/phy/apps/base.py", line 1638, in create_gui
    self.supervisor.attach(gui)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/phy/cluster/supervisor.py", line 941, in attach
    self._create_views(
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/phy/cluster/supervisor.py", line 760, in _create_views
    gui, data=self.cluster_info, columns=self.columns, sort=sort)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/phy/cluster/supervisor.py", line 916, in cluster_info
    return [self.get_cluster_info(cluster_id) for cluster_id in self.clustering.cluster_ids]
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/phy/cluster/supervisor.py", line 916, in <listcomp>
    return [self.get_cluster_info(cluster_id) for cluster_id in self.clustering.cluster_ids]
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/phy/cluster/supervisor.py", line 745, in get_cluster_info
    out[key] = func(cluster_id)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/phy/utils/context.py", line 154, in memcached
    out = f(*args, **kwargs)
  File "/Users/gaelle/Documents/Git/int-brain-lab/iblapps/launch_phy/plugins/phy_plugin.py", line 80, in mean_amp_true
    waveforms = controller._get_waveforms_with_n_spikes(
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/joblib/memory.py", line 591, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/joblib/memory.py", line 483, in _cached_call
    func_id, args_id = self._get_output_identifiers(*args, **kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/joblib/memory.py", line 620, in _get_output_identifiers
    argument_hash = self._get_argument_hash(*args, **kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/joblib/memory.py", line 614, in _get_argument_hash
    return hashing.hash(filter_args(self.func, self.ignore, args, kwargs),
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/joblib/func_inspect.py", line 268, in filter_args
    raise ValueError(
ValueError: Wrong number of arguments for _get_waveforms_with_n_spikes(self, cluster_id, n_spikes_waveforms, batch_size_waveforms, current_filter=None):
     _get_waveforms_with_n_spikes(<phy.apps.template.gui.TemplateController object at 0x7fe17bff97c0>, 0, 100, ) was called.
```

**Comment by rossant** [comment]
Are you on master of iblapps? I pushed a tentative fix 5 days ago

**Comment by GaelleChapuis** [comment]
Yes I am on master, with your tentative fix incorporated.

**Comment by rossant** [comment]
Something doesn't seem right, look at the error message, it says the signature of the function is `ValueError: Wrong number of arguments for _get_waveforms_with_n_spikes(self, cluster_id, n_spikes_waveforms, batch_size_waveforms, current_filter=None):`

But [here is the actual code](https://github.com/cortex-lab/phy/blob/master/phy/apps/base.py#L181):

```
    def _get_waveforms_with_n_spikes(
            self, cluster_id, n_spikes_waveforms, current_filter=None):
```

Somehow it's not using the correct version of phy (latest master, like phylib).

**Comment by GaelleChapuis** [comment]
I have 3 versions of base.py:

One in an old copy-pasted Git folder (Archive) that contains:
```
    def _get_waveforms_with_n_spikes(
            self, cluster_id, n_spikes_waveforms, batch_size_waveforms, current_filter=None):
```

one in int-brain-lab that contains:
```
    def _get_waveforms_with_n_spikes(
            self, cluster_id, n_spikes_waveforms, current_filter=None):
```

and one in the anaconda >...> iblenv >...> apps that contains:
```
    def _get_waveforms_with_n_spikes(
            self, cluster_id, n_spikes_waveforms, batch_size_waveforms, current_filter=None):
```

I can delete the Archive folder, but I am not sure how to set properly the anaconda base.py .
Will close this issue as it's specific to my install, not a general issue.
