### ISSUE TITLE
[Bug report] - KeyError: 'brainLocationIds_ccf_2017' in repeated site session

### ISSUE THREAD

**Issue by SebastianBruijns** [int-brain-lab/iblenv#175]
While re-downloading repeated site data from sessions that should have no issues, I ran into error, this is the code:

```
from oneibl.one import ONE
from brainbox.io.one import load_spike_sorting_with_channel
one = ONE()
eid = '4b00df29-3769-43be-bb40-128b1cba6d35'
load_spike_sorting_with_channel(eid, one=one, force=True)
```

This is the error:

```
2021-01-26 15:40:42.305 INFO     [one.py:250] Did not find local files for spikes and clusters for /kyb/agpd/sbruijns/Downloads/FlatIron/churchlandlab/Subjects/CSHL052/2020-02-21/001 and probe00. Downloading....
/apps/conda/sbruijns/envs/iblenv/lib/python3.8/site-packages/pandas/core/indexing.py:1786: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, val, pi)
2021-01-26 15:40:44.642 INFO     [one.py:250] Did not find local files for spikes and clusters for /kyb/agpd/sbruijns/Downloads/FlatIron/churchlandlab/Subjects/CSHL052/2020-02-21/001 and probe01. Downloading....
2021-01-26 15:40:47.129 INFO     [one.py:92] Channel locations for probe00 have been resolved. Channel and cluster locations obtained from ephys aligned histology track.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/kyb/agpd/sbruijns/int-brain-lab/ibllib-repo/brainbox/io/one.py", line 363, in load_spike_sorting_with_channel
    channels = load_channel_locations(eid, one=one, probe=probe, aligned=aligned)
  File "/kyb/agpd/sbruijns/int-brain-lab/ibllib-repo/brainbox/io/one.py", line 98, in load_channel_locations
    'atlas_id': chans['brainLocationIds_ccf_2017'],
KeyError: 'brainLocationIds_ccf_2017'

```

**Comment by SebastianBruijns** [comment]
Two errors actually:
1. The key error.
2. But also "A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead" has been cropping up a lot lately, that might also need fixing?
