### ISSUE TITLE
[Bug report] - Cannot download trial data for eid '572a95d1-39ca-42e1-8424-5c9ffcb2df87'

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#178]
**Describe the bug**

Cannot download trial data for eid '572a95d1-39ca-42e1-8424-5c9ffcb2df87'.

error:
```
recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-f344164db80e>", line 1, in <module>
    test = one.load_object(eid, 'trials')
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/oneibl/one.py", line 126, in wrapper
    return method(self, id, *args, **kwargs)
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/oneibl/one.py", line 495, in load_object
    assert not any(x is None for x in out_files), 'failed to download object'
AssertionError: failed to download object
```

There was this original message when attempting the download for the first time (mismatching length in datasets):
```
2021-01-28 16:21:59.576 WARNING  [io.py:303] Inconsistent dimensions for object:trials
(573, 2),    intervals_bpod
(573,),    firstMovement_times
(573,),    contrastLeft
(573,),    probabilityLeft
(573,),    stimOn_times
(573,),    choice
(573,),    stimOff_times
(573,),    rewardVolume
(561,),    itiDuration
(573, 2),    intervals
(573,),    goCue_times
(573,),    feedbackType
(573,),    response_times
(573,),    feedback_times
(573,),    goCueTrigger_times
(573,),    contrastRight
```

And this warning occurs after re-attempting downloading:
```
2021-01-28 16:29:18.289 WARNING  [one.py:788]  local md5 or size mismatch, re-downloading /Users/gaelle/Downloads/FlatIron/cortexlab/Subjects/KS020/2020-02-07/001/alf/_ibl_trials.response_times.npy
2021-01-28 16:29:20.290 WARNING  [one.py:745] alf/_ibl_trials.itiDuration.npy exist flag or url not found in Alyx
2021-01-28 16:29:23.553 WARNING  [one.py:788]  local md5 or size mismatch, re-downloading /Users/gaelle/Downloads/FlatIron/cortexlab/Subjects/KS020/2020-02-07/001/alf/_ibl_trials.goCueTrigger_times.npy
2021-01-28 16:29:23.739 WARNING  [one.py:788]  local md5 or size mismatch, re-downloading /Users/gaelle/Downloads/FlatIron/cortexlab/Subjects/KS020/2020-02-07/001/alf/_ibl_trials.intervals.npy
```

**To Reproduce**
`one.load_object(eid, 'trials')`

**Comment by nbonacchi** [comment]
try to 
one.load(..., **download_only=True, clobber=True**, ...)
looks like the iti duration is off by some nument of trials and it will not fit nicely with the rest of the trials table

**Comment by oliche** [comment]
@GaelleChapuis could you please restart the EphysTrials job from Alyx ?

**Comment by nbonacchi** [comment]
@oliche I relaunched it now, but last run was 2 days ago save version of ibllib, I believe the result will be the same

**Comment by oliche** [comment]
Thanks Nicco, I just think this is something we should outsource to users.

**Comment by GaelleChapuis** [comment]
Same error, and yes indeed the EphysTrial extraction is on the latest version 1.5.37
https://alyx.internationalbrainlab.org/admin/jobs/task/3aef3ad0-1bbc-408d-8bf5-95526e6f981d/change/

I'll try deleting my local folder and re-download.

**Comment by GaelleChapuis** [comment]
Getting the same error after having deleted the whole KS020 folder on my local Flatiron folder.

Full output below

```
trials_all = one.load_object(eid, 'trials')
2021-01-29 14:24:28.240 WARNING  [one.py:745] alf/_ibl_trials.itiDuration.npy exist flag or url not found in Alyx
Downloading: /Users/gaelle/Downloads/FlatIron/cortexlab/Subjects/KS020/2020-02-07/001/alf/_ibl_trials.contrastRight.a4598042-272e-47bf-9e4c-642e395522a4.npy Bytes: 2840
Downloading: /Users/gaelle/Downloads/FlatIron/cortexlab/Subjects/KS020/2020-02-07/001/alf/_ibl_trials.probabilityLeft.d38d8056-cd1d-420e-8456-42c1cf15c87e.npy Bytes: 2840Downloading: /Users/gaelle/Downloads/FlatIron/cortexlab/Subjects/KS020/2020-02-07/001/alf/_ibl_trials.feedback_times.1d11f9fd-cd74-40ec-8dcf-7e7eef1bb599.npy Bytes: 2840
Downloading: /Users/gaelle/Downloads/FlatIron/cortexlab/Subjects/KS020/2020-02-07/001/alf/_ibl_trials.feedbackType.a79177bd-d9fe-47cf-9684-44968d7a06a0.npy Bytes: 2840
Downloading: /Users/gaelle/Downloads/FlatIron/cortexlab/Subjects/KS020/2020-02-07/001/alf/_ibl_trials.intervals_bpod.c01ec42d-9b40-40dc-9a98-57ed4c40dfcc.npy Bytes: 5552
Downloading: /Users/gaelle/Downloads/FlatIron/cortexlab/Subjects/KS020/2020-02-07/001/alf/_ibl_trials.goCueTrigger_times.304738a6-9753-4607-8110-d9e3fa2adfde.npy Bytes: 2840
Downloading: /Users/gaelle/Downloads/FlatIron/cortexlab/Subjects/KS020/2020-02-07/001/alf/_ibl_trials.response_times.d065fbe8-55e2-4877-a63c-6f3722abee91.npy Bytes: 2840
Downloading: /Users/gaelle/Downloads/FlatIron/cortexlab/Subjects/KS020/2020-02-07/001/alf/_ibl_trials.stimOn_times.058c8995-f672-462b-9c1b-84644d533834.npy Bytes: 2840
Downloading: /Users/gaelle/Downloads/FlatIron/cortexlab/Subjects/KS020/2020-02-07/001/alf/_ibl_trials.choice.c5f4df7a-d555-408a-8a9c-6b7830420d8c.npy Bytes: 2840
Downloading: /Users/gaelle/Downloads/FlatIron/cortexlab/Subjects/KS020/2020-02-07/001/alf/_ibl_trials.goCue_times.e2cdc0ac-ee24-45b8-b7af-6a1247f29ab3.npy Bytes: 2840
Downloading: /Users/gaelle/Downloads/FlatIron/cortexlab/Subjects/KS020/2020-02-07/001/alf/_ibl_trials.contrastLeft.f9192175-424a-4e5a-8dd6-6942dc2f5672.npy Bytes: 2840
Downloading: /Users/gaelle/Downloads/FlatIron/cortexlab/Subjects/KS020/2020-02-07/001/alf/_ibl_trials.firstMovement_times.60090e85-753e-41cc-a7f3-575304a45ad0.npy Bytes: 2840
Downloading: /Users/gaelle/Downloads/FlatIron/cortexlab/Subjects/KS020/2020-02-07/001/alf/_ibl_trials.stimOff_times.069810f6-8211-4c58-957f-9fcba387dc7f.npy Bytes: 2840
Downloading: /Users/gaelle/Downloads/FlatIron/cortexlab/Subjects/KS020/2020-02-07/001/alf/_ibl_trials.rewardVolume.e5a2705b-6c6c-4f7b-9a57-d8ae90fa0df4.npy Bytes: 2840
Downloading: /Users/gaelle/Downloads/FlatIron/cortexlab/Subjects/KS020/2020-02-07/001/alf/_ibl_trials.intervals.1140f050-5e37-4a0b-ba1a-ce1c0acf84f0.npy Bytes: 5552
 |████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0% Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-00060c99c8e3>", line 1, in <module>
    trials_all = one.load_object(eid, 'trials')
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/oneibl/one.py", line 126, in wrapper
    return method(self, id, *args, **kwargs)
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/oneibl/one.py", line 495, in load_object
    assert not any(x is None for x in out_files), 'failed to download object'
AssertionError: failed to download object
```

**Comment by mayofaulkner** [comment]
Looks like this is the offending dataset https://alyx.internationalbrainlab.org/admin/data/dataset/c595dbe2-5dac-47a1-9e83-661064aa2a92/change/. It doesn't exist on local server, only on flatiron and so flags are set to false when task was reset. I'll update the flatiron flag now to exist so the error goes away and you can load_object and will investigate if there are others like this and see if it's an import issue

**Comment by GaelleChapuis** [comment]
Now working, thanks !
