### ISSUE TITLE
[Bug report] - Camera data: 'failed to download object' for eid='00d3c9ea-2c91-44c2-b03e-6dfec5e08f27'

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#197]
**Describe the bug**
I cannot download the camera data using ONE for a specific eid.
Code snippet:

```
eid='00d3c9ea-2c91-44c2-b03e-6dfec5e08f27'
object_one = 'leftCamera'
one.load_object(eid, obj=object_one, collection='alf')
```

Error:
```
2021-02-15 15:06:43.155 WARNING  [one.py:745] alf/_ibl_leftCamera.dlc.pqt exist flag or url not found in Alyx
Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-897604fb7478>", line 1, in <module>
    one.load_object(eid, obj=object_one, collection='alf')
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/oneibl/one.py", line 126, in wrapper
    return method(self, id, *args, **kwargs)
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/oneibl/one.py", line 495, in load_object
    assert not any(x is None for x in out_files), 'failed to download object'
AssertionError: failed to download object
```

The `.times` data is on FI (https://ibl.flatironinstitute.org/hoferlab/Subjects/SWC_061/2020-12-02/001/alf/ , _ibl_leftCamera.times.0c168b13-49cd-4421-82d0-64eb22d2ddc0.npy ) ; I do not understand why not having the `.dlc` data is causing an issue (i.e., just the `.times` data could be downloaded via the one command).
Manual download (by clicking on the `.times` file) seems fine.

**Comment by GaelleChapuis** [comment]
I circumvented the issue using `one.load` instead of `one.load_object` :

```
    ds = one.alyx.rest('datasets', 'list', session=eid, django='name__icontains,leftCamera.dlc')
    if len(ds) > 0:  # Dataset exists
        # one.load_object(eid, obj=object_one, collection='alf') [PREVIOUS LOAD METHOD WHICH DOES NOT WORK]
        data_load = one.load(eid, dataset_types=ds[0]['name'])
        if data_load[0] is not None: # data exists
            cam_obj = alf.io.load_object(
                              alf_path,
                              object=object_one,
                              namespace='ibl')
```

**Comment by GaelleChapuis** [comment]
I had to actually use the key 'dataset_type'  which made the query less specific:
`data_load = one.load(eid, dataset_types=ds[0]['dataset_type'])`
