### ISSUE TITLE
[Usage question] - Find sessions with multiple extended_qc fields

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#198]
**Describe the question you have**
I would like to check whether certains fields of the `session__extended_qc` exist, using a single ONE query.

For example:
`sess = one.alyx.rest('sessions', 'list', django=f'extended_qc__icontains,if_mean_in_box,extended_qc__icontains,whisker_pupil_block')`
                                  
This does not work however, as using multiple times the filter `extended_qc__icontains` raises an HTTP error.

What is the correct nomenclature?

**Is your question related to a specific product?**
ONE

**Additional context**
I need to find the sessions that have multiple QC computed.

**Comment by rossant** [comment]
Could you copy the full error message?

**Comment by GaelleChapuis** [comment]
```
sess_all = one.alyx.rest('sessions', 'list', task_protocol='ephys',
   ...:                          django=f'project__name__icontains,ibl_neuropixel_brainwide_01,'
   ...:                                 f'data_dataset_session_related__name__icontains,Camera.raw,'
   ...:                                 f'extended_qc__icontains,if_mean_in_box,extended_qc__icontains,file_headers')
2021-02-16 15:52:33.911 ERROR    [webclient.py:258] https://alyx.internationalbrainlab.org/sessions?&task_protocol=ephys&django=project__name__icontains,ibl_neuropixel_brainwide_01,data_dataset_session_related__name__icontains,Camera.raw,extended_qc__icontains,if_mean_in_box,extended_qc__icontains,file_headers
2021-02-16 15:52:33.915 ERROR    [webclient.py:259] {"status_code":500,"detail":"Duplicated fields in \"project__name__icontains,ibl_neuropixel_brainwide_01,data_dataset_session_related__name__icontains,Camera.raw,extended_qc__icontains,if_mean_in_box,extended_qc__icontains,file_headers\""}
Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-0e1195dcc7ed>", line 1, in <module>
    sess_all = one.alyx.rest('sessions', 'list', task_protocol='ephys',
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/oneibl/webclient.py", line 466, in rest
    return self.get('/' + url)
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/oneibl/webclient.py", line 321, in get
    rep = self._generic_request(requests.get, rest_query)
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/oneibl/webclient.py", line 260, in _generic_request
    raise(requests.HTTPError(r))
requests.exceptions.HTTPError: <Response [500]>
```
