### ISSUE TITLE
Video crashes during ephys session due to "no space"

### ISSUE THREAD

**Issue by noamroth** [int-brain-lab/iblenv#207]
In the middle of an ephys session, the video acquisition crashed with the following error: 

```
Unhandled Exception: System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Bonsai.IO.WriterDisposable`1.DisposeInternal()
   at Bonsai.IO.WriterDisposable`1.<Dispose>b__9_0()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.EventLoopScheduler.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

I checked that there was plenty of space on the PC before running the session (and in fact, this was the first full session I've run, so there is no video data yet, there is no reason for the disk to be full...) 

I'm not sure when exactly during the session it crashed -- I was paying attention to the mouse and neural data, but bonsai/camera views definitely started up normally.

**Comment by GaelleChapuis** [comment]
@noamroth does this happen routinely (i.e. each time you run an ephysSession, video acquisition crashes in the middle of it)?
Could you post here which version of the code (Bonsai and all ibl libraries installed) you have on your rig ?
Thanks !
