### ISSUE TITLE
[Bug report] - Error when disabling AUTOMATIC_CALIBRATION setting

### ISSUE THREAD

**Issue by sanworks** [int-brain-lab/iblenv#23]
In each protocol's task_settings.py file, setting AUTOMATIC_CALIBRATION to 'False' used to allow the trainingChoiceWorld protocol to run without a calibration table on the local machine. This was useful for bench testing.

In the current version, this results in a crash:

`Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 21, in <module>
    sph = SessionParamHandler(task_settings, user_settings)
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\session_params.py", line 81, in __init__
    self.CALIB_FUNC_RANGE = adaptive.init_calib_func_range()
  File "C:\iblrig\iblrig\adaptive.py", line 72, in init_calib_func_range
    min_open_time = PARAMS["WATER_CALIBRATION_RANGE"][0]
TypeError: 'NoneType' object is not subscriptable`

**Comment by nbonacchi** [comment]
Thanks for reporting, that indeed should not happen. If flag says OFF rig should use fixed value for valve_opening_time. I'll look into it in light of the new organization of the launching of tasks I'm working on, the ability to run without calibration is probably going away in lfavor of a default calibration value with something like a 1900's date that will issues a warning when launched as the calibration is too old but will still run...
