### ISSUE TITLE
bpod fail to run on certain subject

### ISSUE THREAD

**Issue by Petrina-Lau** [int-brain-lab/iblenv#231]
On one of my training rig, when I run trainingCW on one particular subject (PL007), I ran into the following error on 2 consecutive days (after the PC ran out of memory last time it was used to train this animal). The same rig and protocol works fine for other subjects (PL001, PL004 and _iblrig_test_mouse). 

Yesterday, bpod ran trainingCW for the first 2 subjects, then got into an error for the 3rd subject (PL007). I re-ran it on _iblrig_test_mouse after that but bpod failed to start a training section. Then, I followed the discussion on slack about JsonDecodeError, .iblrig_params.json was emptied. Then i followed the recommendation, deleted the parameter.json and ran a new protocol and recalibrated everything. Today it worked fine for the first 2 subjects but ran into the same error again for the 3rd subject. This time the .iblrig_params.json was not emptied. The error message is as below: 

Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 21, in <module>
    sph = SessionParamHandler(task_settings, user_settings)
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\session_params.py", line 71, in __init__
    self.LAST_TRIAL_DATA = iotasks.load_data(self.PREVIOUS_SESSION_PATH)
  File "c:\iblrig\iblrig\iotasks.py", line 131, in load_data
    trial_data = raw.load_data(session_folder)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\ibllib\io\raw_data_loaders.py", line 97, in load_data
    data = jsonable.read(path)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\ibllib\io\jsonable.py", line 8, in read
    data.append(json.loads(line))
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-04-27 15:29:54.10 INFO     [params.py:135] Writing {'NAME': '_iblrig_hausserlab_behavior_1', 'COM_BPOD': 'COM9', 'COM_ROTARY_ENCODER': 'COM7', 'COM_F2TTL': 'COM6', 'F2TTL_DARK_THRESH': 219.0, 'F2TTL_LIGHT_THRESH': 179.0, 'F2TTL_CALIBRATION_DATE': '2021-04-26', 'WATER_CALIBRATION_RANGE': [50.0, 200.0], 'WATER_CALIBRATION_OPEN_TIMES': [50.0, 100.0, 150.0, 200.0], 'WATER_CALIBRATION_WEIGHT_PERDROP': [0.3333333333333333, 0.8, 1.6666666666666665, 2.3333333333333335], 'WATER_CALIBRATION_DATE': '2021-04-27', 'IBLRIG_VERSION': None, 'SCREEN_FREQ_TARGET': None, 'SCREEN_FREQ_TEST_STATUS': None, 'SCREEN_FREQ_TEST_DATE': None, 'BPOD_TTL_TEST_STATUS': None, 'BPOD_TTL_TEST_DATE': None} to c:\iblrig_params\.iblrig_params.json
Connected to https://alyx.internationalbrainlab.org as petrina.lau
2021-04-27 15:29:55.33 INFO     [registration.py:160] creating session for C:\iblrig_data\Subjects\PL004\2020-12-08\001
2021-04-27 15:29:55.228 ERROR    [webclient.py:249] https://alyx.internationalbrainlab.org/users/_iblrig_test_user
2021-04-27 15:29:55.230 ERROR    [webclient.py:250] {"detail":"Not found.","status_code":404}
2021-04-27 15:29:55.230 ERROR    [registration.py:232] User: _iblrig_test_user doesn't exist in Alyx. ABORT
Traceback (most recent call last):
  File "C:\iblrig\scripts\create_session.py", line 42, in <module>
    main()
  File "C:\iblrig\scripts\create_session.py", line 25, in main
    RegistrationClient(one=None).create_sessions(IBLRIG_DATA, dry=False)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\registration.py", line 162, in create_sessions
    self.create_session(flag_file.parent)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\registration.py", line 170, in create_session
    return self.register_session(session_path, file_list=False)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\registration.py", line 233, in register_session
    raise e
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\registration.py", line 230, in register_session
    user = self.one.alyx.rest('users', 'read', id=md["PYBPOD_CREATOR"][0])
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\webclient.py", line 443, in rest
    return self.get('/' + endpoint + '/' + id.split('/')[-1])
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\webclient.py", line 304, in get
    rep = self._generic_request(requests.get, rest_query)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\webclient.py", line 251, in _generic_request
    raise(requests.HTTPError(r))
requests.exceptions.HTTPError: <Response [404]>

**Comment by nbonacchi** [comment]
you seem to be logged in as test user... Alyx will not allow you to register sessions with that user...
```python
2021-04-27 15:29:55.33 INFO [registration.py:160] creating session for C:\iblrig_data\Subjects\PL004\2020-12-08\001
2021-04-27 15:29:55.228 ERROR [webclient.py:249] https://alyx.internationalbrainlab.org/users/_iblrig_test_user
2021-04-27 15:29:55.230 ERROR [webclient.py:250] {"detail":"Not found.","status_code":404}
2021-04-27 15:29:55.230 ERROR [registration.py:232] User: _iblrig_test_user doesn't exist in Alyx. ABORT
```
I think you might have to go into the settings file and change the PYBPOD_USER variable to a valid Alyx user.

**Comment by Petrina-Lau** [comment]
But I was not creating a session for PL004, it was for PL007, yet the error message says I am and the date is wrong also?!
I was using it as petrina.lau not _iblrig_test_user.  

The same training rig was used for PL001, PL004 and PL007, for the previous 2 subjects, it ran alright. Just PL007 got this error. 

Attached was the bpod GUI when it generates the error messages.

![image](https://user-images.githubusercontent.com/61651331/116277414-5abcb800-a77d-11eb-95b5-f1766f06cca7.png)

**Comment by Petrina-Lau** [comment]
This is everything I see after started a protocol for PL007 again today (I thought there might be something wrong with my data folder from last Friday, it has a lot of trial folder but no data inside, may be that's because the bpod crashed due to lack of memory? so I deleted data file from last Friday and copied the data a day before from the server to local PC and ran trainingCW again but it still doesn't work, same error message). 

2021-04-28 08:59:21.143 INFO     [params.py:135] Writing {'NAME': '_iblrig_hausserlab_behavior_1', 'COM_BPOD': 'COM9', 'COM_ROTARY_ENCODER': 'COM7', 'COM_F2TTL': 'COM6', 'F2TTL_DARK_THRESH': 219.0, 'F2TTL_LIGHT_THRESH': 179.0, 'F2TTL_CALIBRATION_DATE': '2021-04-26', 'WATER_CALIBRATION_RANGE': [50.0, 200.0], 'WATER_CALIBRATION_OPEN_TIMES': [50.0, 100.0, 150.0, 200.0], 'WATER_CALIBRATION_WEIGHT_PERDROP': [0.3333333333333333, 0.8, 1.6666666666666665, 2.3333333333333335], 'WATER_CALIBRATION_DATE': '2021-04-27', 'IBLRIG_VERSION': None, 'SCREEN_FREQ_TARGET': None, 'SCREEN_FREQ_TEST_STATUS': None, 'SCREEN_FREQ_TEST_DATE': None, 'BPOD_TTL_TEST_STATUS': None, 'BPOD_TTL_TEST_DATE': None} to c:\iblrig_params\.iblrig_params.json
2021-04-28 08:59:21.204 INFO     [params.py:135] Writing {'NAME': '_iblrig_hausserlab_behavior_1', 'COM_BPOD': 'COM9', 'COM_ROTARY_ENCODER': 'COM7', 'COM_F2TTL': 'COM6', 'F2TTL_DARK_THRESH': 219.0, 'F2TTL_LIGHT_THRESH': 179.0, 'F2TTL_CALIBRATION_DATE': '2021-04-26', 'WATER_CALIBRATION_RANGE': [50.0, 200.0], 'WATER_CALIBRATION_OPEN_TIMES': [50.0, 100.0, 150.0, 200.0], 'WATER_CALIBRATION_WEIGHT_PERDROP': [0.3333333333333333, 0.8, 1.6666666666666665, 2.3333333333333335], 'WATER_CALIBRATION_DATE': '2021-04-27', 'IBLRIG_VERSION': None, 'SCREEN_FREQ_TARGET': None, 'SCREEN_FREQ_TEST_STATUS': None, 'SCREEN_FREQ_TEST_DATE': None, 'BPOD_TTL_TEST_STATUS': None, 'BPOD_TTL_TEST_DATE': None} to c:\iblrig_params\.iblrig_params.json
2021-04-28 08:59:23.614 INFO     [user_input.py:216] Subject weight 31.1
Connected to https://alyx.internationalbrainlab.org as petrina.lau
2021-04-28 08:59:24.330 INFO     [user_input.py:288] One project found for subject PL007: [ibl_neuropixel_brainwide_01]
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 21, in <module>
    sph = SessionParamHandler(task_settings, user_settings)
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\session_params.py", line 71, in __init__
    self.LAST_TRIAL_DATA = iotasks.load_data(self.PREVIOUS_SESSION_PATH)
  File "c:\iblrig\iblrig\iotasks.py", line 131, in load_data
    trial_data = raw.load_data(session_folder)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\ibllib\io\raw_data_loaders.py", line 97, in load_data
    data = jsonable.read(path)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\ibllib\io\jsonable.py", line 8, in read
    data.append(json.loads(line))
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-04-28 08:59:27.710 INFO     [params.py:135] Writing {'NAME': '_iblrig_hausserlab_behavior_1', 'COM_BPOD': 'COM9', 'COM_ROTARY_ENCODER': 'COM7', 'COM_F2TTL': 'COM6', 'F2TTL_DARK_THRESH': 219.0, 'F2TTL_LIGHT_THRESH': 179.0, 'F2TTL_CALIBRATION_DATE': '2021-04-26', 'WATER_CALIBRATION_RANGE': [50.0, 200.0], 'WATER_CALIBRATION_OPEN_TIMES': [50.0, 100.0, 150.0, 200.0], 'WATER_CALIBRATION_WEIGHT_PERDROP': [0.3333333333333333, 0.8, 1.6666666666666665, 2.3333333333333335], 'WATER_CALIBRATION_DATE': '2021-04-27', 'IBLRIG_VERSION': None, 'SCREEN_FREQ_TARGET': None, 'SCREEN_FREQ_TEST_STATUS': None, 'SCREEN_FREQ_TEST_DATE': None, 'BPOD_TTL_TEST_STATUS': None, 'BPOD_TTL_TEST_DATE': None} to c:\iblrig_params\.iblrig_params.json
Connected to https://alyx.internationalbrainlab.org as petrina.lau
2021-04-28 08:59:28.753 INFO     [registration.py:160] creating session for C:\iblrig_data\Subjects\PL004\2020-12-08\001
2021-04-28 08:59:28.954 ERROR    [webclient.py:249] https://alyx.internationalbrainlab.org/users/_iblrig_test_user
2021-04-28 08:59:28.956 ERROR    [webclient.py:250] {"detail":"Not found.","status_code":404}
2021-04-28 08:59:28.957 ERROR    [registration.py:232] User: _iblrig_test_user doesn't exist in Alyx. ABORT
Traceback (most recent call last):
  File "C:\iblrig\scripts\create_session.py", line 42, in <module>
    main()
  File "C:\iblrig\scripts\create_session.py", line 25, in main
    RegistrationClient(one=None).create_sessions(IBLRIG_DATA, dry=False)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\registration.py", line 162, in create_sessions
    self.create_session(flag_file.parent)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\registration.py", line 170, in create_session
    return self.register_session(session_path, file_list=False)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\registration.py", line 233, in register_session
    raise e
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\registration.py", line 230, in register_session
    user = self.one.alyx.rest('users', 'read', id=md["PYBPOD_CREATOR"][0])
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\webclient.py", line 443, in rest
    return self.get('/' + endpoint + '/' + id.split('/')[-1])
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\webclient.py", line 304, in get
    rep = self._generic_request(requests.get, rest_query)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\webclient.py", line 251, in _generic_request
    raise(requests.HTTPError(r))
requests.exceptions.HTTPError: <Response [404]>

**Comment by nbonacchi** [comment]
It looks like there are 2 problems the first error is that the task cannot read the previous session file data.
As it fails it runs the post task scripts that include a registration attempt of a session of an _iblrig_test_mouse, this will not register as the test mouse does not exist on the DB.

For the first problem you can try looking into the previous session data file for that subject and verify why the json decoder cannot read it, is it empty? is it a dud? if it's either you can try deleting this session.

For the second problem the session it's trying to register is probably the session you mentioned previously that you ran as test mouse. this session is under the test mouse folder in a sub folder with the date and number of when you ran the session, this has to move to the proper subject folder and the metadata inside the taskSettings file has to be patched to reflect the actual name of the subject.

If this does not work let me know if you prefer to schedule a remote session so I can help.

**Comment by Petrina-Lau** [comment]
Thanks for getting back to me! 

For the first error. Yes, I did look at the previous session and indeed the data file was empty, so I did delete that and I tried to run this subject again afterward but it still didn't run. 

For the second problem, where in the taskSettings are the metadata? and which particular files/line should I move/correct? I tried starting new sessions for this particular subject in consecutive days before I test the rig and run other subjects. Should it not automatically start a new folder for each day in the correct subject folder when I do that? 

If you could point me to the files, I can try correcting the metadata myself first (I'd need your time-brain on the Ephys rig more, since I am still struggling with the sound card issue there).

**Comment by nbonacchi** [comment]
The data needs to be in the folder of the correct subject name and the subject name in the settings file (C:\iblrig_data\Subjects\<subject_name>\<date>\<number>\raw_behavior_data\_iblrig_taskSettings.raw.json) needs to be updated to the correct subject.

The subject name is in a lot of places look to the variables under PYBPOD_SUBJECTS, SUBJECT_NAME, etc (i.e. where the subject name appears) this should be changes to reflect the correct subject name and location of the data prior to registration.
