### ISSUE TITLE
ephys pulses extraction fails ~half the time for sessions when no probe is used

### ISSUE THREAD

**Issue by cskrasniak** [int-brain-lab/iblenv#243]
As far as I can tell this mostly happens on sessions I run under the phys protocol but when I am not actually recording from a probe. Ephys pulse extraction fails about half the time with the following error:

```
2021-06-15 13:58:57,777,777 INFO [tasks.py:74] Starting job <class 'ibllib.pipes.ephys_preprocessing.EphysPulses'>
2021-06-15 13:58:57,778,778 INFO [tasks.py:77] running ibllib version 1.10.4
2021-06-15 13:58:57,790,790 ERROR [tasks.py:85] Traceback (most recent call last):
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages/ibllib/pipes/tasks.py", line 82, in run
self.outputs = self._run(**kwargs)
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages/ibllib/pipes/ephys_preprocessing.py", line 47, in _run
status, sync_files = sync_probes.sync(self.session_path)
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages/ibllib/ephys/sync_probes.py", line 44, in sync
return version3A(ses_path, **kwargs)
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages/ibllib/ephys/sync_probes.py", line 98, in version3A
iref = np.argmax(d.nsync)
File "<__array_function__ internals>", line 6, in argmax
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1188, in argmax
return _wrapfunc(a, 'argmax', axis=axis, out=out)
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
return bound(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence

2021-06-15 13:58:57,791,791 INFO [tasks.py:86] Job <class 'ibllib.pipes.ephys_preprocessing.EphysPulses'> errored
2021-06-15 13:58:57,791,791 INFO [tasks.py:96] N outputs: 0
2021-06-15 13:58:57,791,791 INFO [tasks.py:97] --- 0.012423515319824219 seconds run-time ---
```
This seems to be avoidable because there are no probes recording so we shouldn't need to sync them

**Comment by cskrasniak** [comment]
example session here: https://alyx.internationalbrainlab.org/admin/jobs/task/9e61fe9e-4500-43eb-9ab3-b53893c0171e/change/

**Comment by juhuntenburg** [comment]
@cskrasniak the example task you linked went through in a rerun. Is the general problem still persisting?

**Comment by k1o0** [comment]
No response in >1 month, closing for now.  Feel free to re-open when necessary.
