### ISSUE TITLE
Example bug - visualization3D_repeated_site

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#3]
Cannot run example
https://github.com/int-brain-lab/ibllib/blob/develop/examples/one/histology/visualization3D_repeated_site.py 

**Error log**
```
Traceback (most recent call last):
  File "/Applications/anaconda3/anaconda3/envs/iblenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-ca435e83a3a7>", line 38, in <module>
    channels = bbone.load_channel_locations(eid=ses, one=one, probe=probe_label)[probe_label]
  File "/Users/gaelle/Documents/Git/ibllib/brainbox/io/one.py", line 69, in load_channel_locations
    channel_coord = one.load_dataset(eid=eid, dataset_type='channels.localCoordinates')
  File "/Users/gaelle/Documents/Git/ibllib/oneibl/one.py", line 240, in load_dataset
    return self._load(eid, dataset_types=[dataset_type], **kwargs)[0]
  File "/Users/gaelle/Documents/Git/ibllib/oneibl/one.py", line 298, in _load
    eid_str = eid[-36:]
TypeError: unhashable type: 'slice'
```

**Comment by oliche** [comment]
ab01ead8fd43a9115ef2754c1676ac79bb8f97a2
