### ISSUE TITLE
ONE - openalyx - Http error invalid token

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/iblenv#303]
Instantiating ONE on open alyx, and performing an online query gives the following error

```
from one.api import ONE
one = ONE(base_url='https://openalyx.internationalbrainlab.org')
one.alyx.rest('sessions', 'list')
Traceback (most recent call last):
  File "/Users/olivier/opt/anaconda3/envs/iblenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3361, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-a351515ae6dc>", line 1, in <cell line: 1>
    one.alyx.rest('sessions', 'list')
  File "/Users/olivier/Documents/PYTHON/00_IBL/ONE/one/webclient.py", line 944, in rest
    if endpoint not in self.rest_schemes.keys():
  File "/Users/olivier/Documents/PYTHON/00_IBL/ONE/one/webclient.py", line 519, in rest_schemes
    self._rest_schemes = self.get('/docs', expires=timedelta(weeks=1))
  File "/Users/olivier/Documents/PYTHON/00_IBL/ONE/one/webclient.py", line 819, in get
    rep = self._generic_request(requests.get, rest_query, **kwargs)
  File "/Users/olivier/Documents/PYTHON/00_IBL/ONE/one/webclient.py", line 123, in wrapper_decorator
    response = method(alyx_client, *args, **kwargs)
  File "/Users/olivier/Documents/PYTHON/00_IBL/ONE/one/webclient.py", line 573, in _generic_request
    raise requests.HTTPError(r.status_code, rest_query, message, response=r)
requests.exceptions.HTTPError: [Errno 403] /docs: 'Invalid token.'
```

OS: Mac

**Comment by oliche** [comment]
To fix this, I had to remove the the parameters file in 
`~/.one/.openalyx.internationalbrainlab.org`

And then run in Python
```
from one.api import ONE
one = ONE(base_url='https://openalyx.internationalbrainlab.org')
one.setup()
```

This is due to the fact that I changed user. @k1o0 leaving this here for reference, there may be a more elegant way to solve this
