### ISSUE TITLE
[Bug report] - Issue with launching phy/extracting waveforms for phy

### ISSUE THREAD

**Issue by noamroth** [int-brain-lab/iblenv#38]
When trying to launch phy, I get the errors below

I just updated iblenv and I am up to date on the develop branch of iblapps. 
I have gotten this for two sessions: '-e aad23144-0e52-4eac-80c5-c4ee2decb198 -p probe01', and '-s KS022 -d 2019-12-10 -n 1 -p probe00'

```
Traceback (most recent call last):
  File "C:\Installs\envs\iblenv\lib\site-packages\joblib\func_inspect.py", line 281, in filter_args
    arg_dict[arg_name] = arg_defaults[position]
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "int-brain-lab\iblapps\launch_phy\phy_launcher.py", line 100, in <module>
    launch_phy(str(args.probe_label), eid=str(args.eid))
  File "int-brain-lab\iblapps\launch_phy\phy_launcher.py", line 74, in launch_phy
    gui = controller.create_gui()
  File "C:\Installs\envs\iblenv\lib\site-packages\phy\apps\base.py", line 1638, in create_gui
    self.supervisor.attach(gui)
  File "C:\Installs\envs\iblenv\lib\site-packages\phy\cluster\supervisor.py", line 942, in attach
    gui=gui, sort=gui.state.get('ClusterView', {}).get('current_sort', None))
  File "C:\Installs\envs\iblenv\lib\site-packages\phy\cluster\supervisor.py", line 760, in _create_views
    gui, data=self.cluster_info, columns=self.columns, sort=sort)
  File "C:\Installs\envs\iblenv\lib\site-packages\phy\cluster\supervisor.py", line 916, in cluster_info
    return [self.get_cluster_info(cluster_id) for cluster_id in self.clustering.cluster_ids]
  File "C:\Installs\envs\iblenv\lib\site-packages\phy\cluster\supervisor.py", line 916, in <listcomp>
    return [self.get_cluster_info(cluster_id) for cluster_id in self.clustering.cluster_ids]
  File "C:\Installs\envs\iblenv\lib\site-packages\phy\cluster\supervisor.py", line 745, in get_cluster_info
    out[key] = func(cluster_id)
  File "C:\Installs\envs\iblenv\lib\site-packages\phy\utils\context.py", line 154, in memcached
    out = f(*args, **kwargs)
  File "C:\Users\Steinmetz Lab User\int-brain-lab\iblapps\launch_phy\phy_plugin.py", line 81, in mean_amp_true
    n_spikes_waveforms=100)['data'].data
  File "C:\Installs\envs\iblenv\lib\site-packages\joblib\memory.py", line 568, in __call__
    return self._cached_call(args, kwargs)[0]
  File "C:\Installs\envs\iblenv\lib\site-packages\joblib\memory.py", line 483, in _cached_call
    func_id, args_id = self._get_output_identifiers(*args, **kwargs)
  File "C:\Installs\envs\iblenv\lib\site-packages\joblib\memory.py", line 589, in _get_output_identifiers
    argument_hash = self._get_argument_hash(*args, **kwargs)
  File "C:\Installs\envs\iblenv\lib\site-packages\joblib\memory.py", line 583, in _get_argument_hash
    return hashing.hash(filter_args(self.func, self.ignore, args, kwargs),
  File "C:\Installs\envs\iblenv\lib\site-packages\joblib\func_inspect.py", line 288, in filter_args
    _function_called_str(name, args, kwargs))
ValueError: Wrong number of arguments for _get_waveforms_with_n_spikes(self, cluster_id, n_spikes_waveforms, batch_size_waveforms, current_filter=None):
     _get_waveforms_with_n_spikes(<phy.apps.template.gui.TemplateController object at 0x0000024EA4391848>, 0, n_spikes_waveforms=100) was called.
```

**Comment by rossant** [comment]
Might be a problem with the cache, can you locate the `.phy`  subfolder inside the data directory and delete it ?

**Comment by noamroth** [comment]
No, unfortunately this did not help. (just to make sure,  this was the data directory where I deleted the .phy folder: C:\Users\Steinmetz Lab User\Downloads\FlatIron\cortexlab\Subjects\KS023\2019-12-10\001\alf\probe01)

**Comment by rossant** [comment]
1. Are you on master on both phy and phylib?
2. Could you try removing `n_spikes_waveforms=` in https://github.com/int-brain-lab/iblapps/blob/develop/launch_phy/phy_plugin.py#L81?

**Comment by noamroth** [comment]
1) yes, I am, and made sure that I am up to date.
2) I tried removing that and I still get this error below. I also tried removing the argument entirely, and still did not work. 



Traceback (most recent call last):
  File "C:\Installs\envs\iblenv\lib\site-packages\joblib\func_inspect.py", line 281, in filter_args
    arg_dict[arg_name] = arg_defaults[position]
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "int-brain-lab\iblapps\launch_phy\phy_launcher.py", line 100, in <module>
    launch_phy(str(args.probe_label), eid=str(args.eid))
  File "int-brain-lab\iblapps\launch_phy\phy_launcher.py", line 74, in launch_phy
    gui = controller.create_gui()
  File "C:\Installs\envs\iblenv\lib\site-packages\phy\apps\base.py", line 1638, in create_gui
    self.supervisor.attach(gui)
  File "C:\Installs\envs\iblenv\lib\site-packages\phy\cluster\supervisor.py", line 942, in attach
    gui=gui, sort=gui.state.get('ClusterView', {}).get('current_sort', None))
  File "C:\Installs\envs\iblenv\lib\site-packages\phy\cluster\supervisor.py", line 760, in _create_views
    gui, data=self.cluster_info, columns=self.columns, sort=sort)
  File "C:\Installs\envs\iblenv\lib\site-packages\phy\cluster\supervisor.py", line 916, in cluster_info
    return [self.get_cluster_info(cluster_id) for cluster_id in self.clustering.cluster_ids]
  File "C:\Installs\envs\iblenv\lib\site-packages\phy\cluster\supervisor.py", line 916, in <listcomp>
    return [self.get_cluster_info(cluster_id) for cluster_id in self.clustering.cluster_ids]
  File "C:\Installs\envs\iblenv\lib\site-packages\phy\cluster\supervisor.py", line 745, in get_cluster_info
    out[key] = func(cluster_id)
  File "C:\Installs\envs\iblenv\lib\site-packages\phy\utils\context.py", line 154, in memcached
    out = f(*args, **kwargs)
  File "C:\Users\Steinmetz Lab User\int-brain-lab\iblapps\launch_phy\phy_plugin.py", line 81, in mean_amp_true
    100)['data'].data
  File "C:\Installs\envs\iblenv\lib\site-packages\joblib\memory.py", line 568, in __call__
    return self._cached_call(args, kwargs)[0]
  File "C:\Installs\envs\iblenv\lib\site-packages\joblib\memory.py", line 483, in _cached_call
    func_id, args_id = self._get_output_identifiers(*args, **kwargs)
  File "C:\Installs\envs\iblenv\lib\site-packages\joblib\memory.py", line 589, in _get_output_identifiers
    argument_hash = self._get_argument_hash(*args, **kwargs)
  File "C:\Installs\envs\iblenv\lib\site-packages\joblib\memory.py", line 583, in _get_argument_hash
    return hashing.hash(filter_args(self.func, self.ignore, args, kwargs),
  File "C:\Installs\envs\iblenv\lib\site-packages\joblib\func_inspect.py", line 288, in filter_args
    _function_called_str(name, args, kwargs))
ValueError: Wrong number of arguments for _get_waveforms_with_n_spikes(self, cluster_id, n_spikes_waveforms, batch_size_waveforms, current_filter=None):
     _get_waveforms_with_n_spikes(<phy.apps.template.gui.TemplateController object at 0x0000022B4C80E788>, 0, 100, ) was called.


Btw, I am also getting a permission error (below) which I can solve by deleting the data directory (probe01) , but it seems that that shouldn't happen each time you want to reload a session. I can start a new issue with this if it is unrelated, but just thought I'd note it here. 
Traceback (most recent call last):
  File "int-brain-lab\iblapps\launch_phy\phy_launcher.py", line 100, in <module>
    launch_phy(str(args.probe_label), eid=str(args.eid))
  File "int-brain-lab\iblapps\launch_phy\phy_launcher.py", line 56, in launch_phy
    _ = one.load(eid, dataset_types=dtypes, download_only=True)
  File "C:\Users\Steinmetz Lab User\int-brain-lab\ibllib\oneibl\one.py", line 366, in load
    download_only=download_only, clobber=clobber, offline=offline)
  File "C:\Users\Steinmetz Lab User\int-brain-lab\ibllib\oneibl\one.py", line 416, in _load_recursive
    return self._load(eid, **kwargs)
  File "C:\Users\Steinmetz Lab User\int-brain-lab\ibllib\oneibl\one.py", line 154, in _load
    dc = self._make_dataclass(eid_str, dataset_types, **kwargs)
  File "C:\Users\Steinmetz Lab User\int-brain-lab\ibllib\oneibl\one.py", line 457, in _make_dataclass
    dc.local_path[ind] = future.result()
  File "C:\Installs\envs\iblenv\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "C:\Installs\envs\iblenv\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Installs\envs\iblenv\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Steinmetz Lab User\int-brain-lab\ibllib\oneibl\one.py", line 630, in download_dataset
    return self._download_file(url=url, target_dir=target_dir, **kwargs)
  File "C:\Users\Steinmetz Lab User\int-brain-lab\ibllib\oneibl\one.py", line 685, in _download_file
    return remove_uuid_file(local_path)
  File "C:\Users\Steinmetz Lab User\int-brain-lab\ibllib\alf\io.py", line 367, in remove_uuid_file
    file_path.replace(new_path)
  File "C:\Installs\envs\iblenv\lib\pathlib.py", line 1338, in replace
    self._accessor.replace(self, target)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Steinmetz Lab User\\Downloads\\FlatIron\\cortexlab\\Subjects\\KS023\\2019-12-10\\001\\alf\\probe01\\templates.waveforms.96fbf47d-576a-4996-ae55-c6cae63a0a81.npy' -> 'C:\\Users\\Steinmetz Lab User\\Downloads\\FlatIron\\cortexlab\\Subjects\\KS023\\2019-12-10\\001\\alf\\probe01\\templates.waveforms.npy'

**Comment by rossant** [comment]
- OK, it looks the signature is `_get_waveforms_with_n_spikes(cluster_id, n_spikes_waveforms, batch_size_waveforms, current_filter=None)` so could you try adding the batch size waveforms parameter at  https://github.com/int-brain-lab/iblapps/blob/develop/launch_phy/phy_plugin.py#L81 ?
- Yes could you please open a new issue about the permission problem? It seems to be related to ONE and not phy

**Comment by k1o0** [comment]
No follow-up in over a month.  Closing for now.
