### ISSUE TITLE
[Bug report] - TaskQC failing on example session eid

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#45]
**Describe the bug**
I tried this code:
```
from ibllib.qc.task_metrics import TaskQC
from ibllib.qc.qcplots import plot_results
eid = 'fb70ebf7-8175-42b0-9b7a-7c6e8612226e'
qc = TaskQC(eid)
plot_results(qc)
```
using the master branch of ibllib, and I get this error:

```
Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-e0e8434bbe0b>", line 5, in <module>
    plot_results(qc)
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/ibllib/qc/qcplots.py", line 31, in plot_results
    n_trials = qc_obj.extractor.data['intervals_0'].size
KeyError: 'intervals_0'
```

**To Reproduce**
Launch code above.

**Expected behavior**
Plots should appear.

**Add any other context about the problem here.**
This specific eid used to work and was previously given as an example.

**Comment by k1o0** [comment]
Fix on extraTaskQc https://github.com/int-brain-lab/ibllib/commit/ca2bfbd293dec52dc4b93ceecc06b7ac247f5a27

**Comment by GaelleChapuis** [comment]
Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-e0e8434bbe0b>", line 5, in <module>
    plot_results(qc)
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/ibllib/qc/qcplots.py", line 31, in plot_results
    n_trials = qc_obj.extractor.data['intervals_0'].size
KeyError: 'intervals_0'

**Comment by k1o0** [comment]
This is fixed but hasn't been merged yet.  Patience padawan.
