### ISSUE TITLE
[Bug report] - Plot spectrogram not running on given session eid

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#58]
**Describe the bug**
I would like to check the spectrogram of a specific session. Upon doing so, I get this error:

```
2020-09-29 13:18:34.283 WARNING  [one.py:166] dataset _iblmic_audioSpectrogram.frequencies not found for session: 9a7e3a4b-8b68-4817-81f1-adb0f48088eb
2020-09-29 13:18:34.283 WARNING  [one.py:166] dataset _iblmic_audioSpectrogram.power not found for session: 9a7e3a4b-8b68-4817-81f1-adb0f48088eb
2020-09-29 13:18:34.283 WARNING  [one.py:166] dataset _iblmic_audioSpectrogram.times_mic not found for session: 9a7e3a4b-8b68-4817-81f1-adb0f48088eb
Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-2d0c7053ad67>", line 6, in <module>
    'audioSpectrogram', namespace='iblmic')
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/alf/io.py", line 271, in load_object
    files_alf, parts = _ls(alfpath, object, **kwargs)
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/alf/io.py", line 214, in _ls
    raise FileNotFoundError('No {} found in {}'.format(err_str, str(alfpath)))
FileNotFoundError: No object "audioSpectrogram"  found in /Users/gaelle/Downloads/FlatIron/zadorlab/Subjects/CSH_ZAD_029/2020-09-12/001/raw_behavior_data

```
**To Reproduce**
Launch this code: https://github.com/int-brain-lab/ibllib/blob/develop/examples/one/behavior/plot_microphone_spectrogram.py
but with eid:
`eid = '9a7e3a4b-8b68-4817-81f1-adb0f48088eb'`

**Expected behavior**
Spectrogram plot.

**Comment by oliche** [comment]
For ephys sessions we save the compressed microphone file entirely: dtype: `_iblrig_micData.raw`.
So we don't expect the datasets above.

I'll close it for now and we'll see if it needs a new feature.

**Comment by GaelleChapuis** [comment]
The previous example code (linked above, for a behavior rig) does not work anymore for data acquired on an ephys rig since the dataset type is different.

Could someone point me to an example of how to plot such spectrogram for an ephys rig?
Thanks !

**Comment by GaelleChapuis** [comment]
```
"""
For a given session eid (ephys session), plot spectrogram of sound recorded via the microphone.
"""
# Author: Gaelle Chapuis

from ibllib.io.extractors.training_audio import welchogram
import soundfile as sf
import numpy as np
import matplotlib.pyplot as plt
# import alf.io
from oneibl.one import ONE

one = ONE()

dataset_types = ['_iblrig_micData.raw']

eid = '9a7e3a4b-8b68-4817-81f1-adb0f48088eb'  # TEST EXAMPLE

one.load(eid, dataset_types=dataset_types, download_only=True)
session_path = one.path_from_eid(eid)

# -- Get raw data
filename = session_path.joinpath('raw_behavior_data', '_iblrig_micData.raw.flac')

with open(filename, 'rb') as f:
    wav, fs = sf.read(f)

# -- Compute spectrogram
tscale, fscale, W, detect = welchogram(fs, wav)

# -- Put data into single variable
TF = {}

TF['power'] = W.astype(np.single)
TF['frequencies'] = fscale[None, :].astype(np.single)
TF['onset_times'] = detect
TF['times_mic'] = tscale[:, None].astype(np.single)

# # -- Plot spectrogram
tlims = TF['times_mic'][[0, -1]].flatten()
flims = TF['frequencies'][0, [0, -1]].flatten()
fig = plt.figure(figsize=[16, 7])
ax = plt.axes()
im = ax.imshow(20 * np.log10(TF['power'].T), aspect='auto', cmap=plt.get_cmap('magma'),
               extent=np.concatenate((tlims, flims)),
               origin='lower')
ax.set_xlabel(r'Time (s)')
ax.set_ylabel(r'Frequency (Hz)')
plt.colorbar(im)
```
