### ISSUE TITLE
[Bug report] - Error while running QC script

### ISSUE THREAD

**Issue by guidomeijer** [int-brain-lab/iblenv#59]
I run the following QC code on the behavior pc of the ephys rig with updated ibllib version 1.5.11

from ibllib.qc.task_metrics import TaskQC
from ibllib.qc.qcplots import plot_results
session_path = r'C:\\iblrig_data\\Subjects\\ZM_3001\\2020-08-07\\001'
qc = TaskQC(session_path)
qc.load_data(bpod_only=True)  # Extract without FPGA
qc.run()
qc.extractor.data['intervals_0'] = qc.extractor.data['intervals'][:, 0]
plot_results(qc, save_path=session_path)

I get the following error

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    qc.load_data(bpod_only=True)  # Extract without FPGA
  File "C:\Users\IBLUSER\Anaconda3\envs\iblenv\lib\site-packages\ibllib\qc\task_metrics.py", line 57, in load_data
    self.session_path, one=self.one, download_data=download_data, bpod_only=bpod_only)
  File "C:\Users\IBLUSER\Anaconda3\envs\iblenv\lib\site-packages\ibllib\qc\task_extractors.py", line 42, in __init__
    self._ensure_required_data()
  File "C:\Users\IBLUSER\Anaconda3\envs\iblenv\lib\site-packages\ibllib\qc\task_extractors.py", line 66, in _ensure_required_data
    settings = self.one.load(eid, ["_iblrig_taskSettings.raw"], download_only=True)
  File "C:\Users\IBLUSER\Anaconda3\envs\iblenv\lib\site-packages\oneibl\one.py", line 366, in load
    download_only=download_only, clobber=clobber, offline=offline)
  File "C:\Users\IBLUSER\Anaconda3\envs\iblenv\lib\site-packages\oneibl\one.py", line 416, in _load_recursive
    return self._load(eid, **kwargs)
  File "C:\Users\IBLUSER\Anaconda3\envs\iblenv\lib\site-packages\oneibl\one.py", line 154, in _load
    dc = self._make_dataclass(eid_str, dataset_types, **kwargs)
  File "C:\Users\IBLUSER\Anaconda3\envs\iblenv\lib\site-packages\oneibl\one.py", line 457, in _make_dataclass
    dc.local_path[ind] = future.result()
  File "C:\Users\IBLUSER\Anaconda3\envs\iblenv\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\IBLUSER\Anaconda3\envs\iblenv\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\IBLUSER\Anaconda3\envs\iblenv\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\IBLUSER\Anaconda3\envs\iblenv\lib\site-packages\oneibl\one.py", line 630, in download_dataset
    return self._download_file(url=url, target_dir=target_dir, **kwargs)
  File "C:\Users\IBLUSER\Anaconda3\envs\iblenv\lib\site-packages\oneibl\one.py", line 675, in _download_file
    clobber=clobber, offline=offline, return_md5=True)
  File "C:\Users\IBLUSER\Anaconda3\envs\iblenv\lib\site-packages\oneibl\webclient.py", line 111, in http_download_file
    if (len(password) != 0) & (len(username) != 0):
TypeError: object of type 'NoneType' has no len()

**Comment by rossant** [comment]
It looks as if it didn't manage to connect to the HTTP server. What is the terminal output of `from oneibl.one import ONE; ONE()` ?

**Comment by oliche** [comment]
Currently the task QC object works only with a ONE connection. Here you're missing some parameters, namely the HTTP credentials to connect to ibl.flatironinstitute.org

You need to setup your ONE connection as described here: 
https://docs.internationalbrainlab.org/en/latest/02_installation_python.html

**Comment by k1o0** [comment]
Call `TaskQC` with `download_data=False`, then the database won't be used:

```
from ibllib.qc.task_metrics import TaskQC
from ibllib.qc.qcplots import plot_results
session_path = r'C:\iblrig_data\Subjects\ZM_3001\2020-08-07\001'
qc = TaskQC(session_path, download_data=False)
qc.load_data(bpod_only=True) # Extract without FPGA
qc.run()
plot_results(qc, save_path=session_path)
```

Feel free to reopen if you continue having problems.
