### ISSUE TITLE
Error adding subject to pybpod

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblenv#67]
To replicate:
1. In the 'Subjects' menu item in pybpod, right-click and select 'Add subject'
2. In the 'Details' section, fill in the name, then select the setup (e.g. _iblrig_tasks > trainingChoiceWorld)
3. Click 'Run'

```
Auto saving project
Object of type UUID is not JSON serializable
Traceback (most recent call last):
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pybpodgui_api\models\setup\setup_com.py", line 95, in run_task
    detached=self.detached
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pybpodgui_plugin\models\board\board_com.py", line 55, in run_task
    flag = super(BoardCom, self).run_task(session, board_task, workspace_path, detached)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pybpodgui_api\models\board\board_com.py", line 132, in run_task
    xt_subject.append(sbj.toJSON())
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pybpod_alyx_module\models\subject\alyx_subject.py", line 61, in toJSON
    return super().toJSON()
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pybpodgui_api\models\subject\subject_io.py", line 70, in toJSON
    return json.dumps(data)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\sca\formats\json.py", line 146, in dumps
    return json.dumps(data, sort_keys=sort_keys)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UUID is not JSON serializable
```

**Comment by nbonacchi** [comment]
This is a bug where creating a new subject will write to disk correctly, read from disk correctly but read from memory incorrectly. On creation it will pass the newly created UUID object to the read method that does not know to deal with UUID objects.
Closing and reopening the GUI should flush the memory and force a reload from the json file.
