### ISSUE TITLE
[Bug report] - Task metrics bug with np.nan_to_num()

### ISSUE THREAD

**Issue by rossant** [int-brain-lab/iblenv#79]
Tasks have failed lately, for example https://alyx.internationalbrainlab.org/admin/jobs/task/4acc6f96-0b38-4d33-b368-f437c0fa8802/change/

```
2020-10-16 17:41:08,600,600 INFO [task_extractors.py:120] Extracting session: /mnt/s0/Data/Subjects/SWC_050/2020-10-16/001
2020-10-16 17:41:08,600,600 INFO [task_extractors.py:94] Loading raw data from /mnt/s0/Data/Subjects/SWC_050/2020-10-16/001
2020-10-16 17:41:09,031,31 INFO [task_metrics.py:80] Session /mnt/s0/Data/Subjects/SWC_050/2020-10-16/001: Running QC on behavior data...
2020-10-16 17:41:11,029,29 ERROR [tasks.py:76] Traceback (most recent call last):
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.6/site-packages/ibllib/pipes/tasks.py", line 72, in run
self.outputs = self._run(**kwargs)
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.6/site-packages/ibllib/pipes/training_preprocessing.py", line 56, in _run
qc.run(update=True)
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.6/site-packages/ibllib/qc/task_metrics.py", line 99, in run
self.compute(**kwargs)
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.6/site-packages/ibllib/qc/task_metrics.py", line 87, in compute
min_qt=self.extractor.settings.get('QUIESCENT_PERIOD') or 0.2
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.6/site-packages/ibllib/qc/task_metrics.py", line 259, in get_bpodqc_metrics_frame
qc_metrics_map = {prefix + k[6:]: fn(data, **kwargs) for k, fn in checks}
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.6/site-packages/ibllib/qc/task_metrics.py", line 259, in <dictcomp>
qc_metrics_map = {prefix + k[6:]: fn(data, **kwargs) for k, fn in checks}
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.6/site-packages/ibllib/qc/task_metrics.py", line 713, in check_errorCue_delays
metric = np.nan_to_num(data["errorCue_times"] - data["errorCueTrigger_times"], nan=np.inf)
TypeError: nan_to_num() got an unexpected keyword argument 'nan'
```

**Comment by k1o0** [comment]
The issue is these rigs are using an older version of numpy.  We should be able to increase the minimum version, right?

**Comment by k1o0** [comment]
Environment is reinstalled daily, so I will iterate numpy to v1.19 in the requirements

**Comment by k1o0** [comment]
https://github.com/int-brain-lab/ibllib/pull/221/commits/bcebba101ccead18c7247b5737efc42c77c6f19f
