### ISSUE TITLE
[Bug report] - import ibllib fails after clean install

### ISSUE THREAD

**Issue by nantille** [int-brain-lab/iblenv#81]
**Describe the bug**
After a full and clean install of conda and the whole ibl environment, running `import ibllib` fails due to numpy and blas, evne if the current system is not running on AMD. (MacOS Mojave on Macbook Pro with Intel Core i7)

**To Reproduce**
Install conda and follow IBL env installation procedure (https://github.com/int-brain-lab/iblenv)

**Expected behavior**
`import ibllib` works

**Desktop:**
 - OS: MacOS Mojave

**Additional context**
None

**Comment by nantille** [comment]
After looking at likely issues, some people mentioned on stackoverflow that existing python versions could be an issue, which is strange since conda runs in its own environment.

I cannot remove my Python 3.7 installation as other software depend on it, and IBL Env installs Python 3.8.

The solution was given [on this post by Andrew J Winkler](https://stackoverflow.com/a/37110747). Simply:
```
conda activate iblenv
pip uninstall numpy
pip install numpy
```
Make sure that pip is the one from iblenv, not from another Python install.

**Comment by nantille** [comment]
Something veeeery strange is happening.

I thought everything was OK but this code fails in interactive python (within iblenv).
```
import ibllib
import numpy as np
a = np.array([])
```

Yields:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'numpy' has no attribute 'array'
```

**Comment by nantille** [comment]
I have removed the Python3.7 install with Homebrew and only got the default 2.7 that ships with MacOS.
Problem is still here so I tried `conda uninstall numpy` which listed most packages that depend on it for uninstall. I went on with it and then did `pip install numpy`. Now numpy works but of course I miss all the modules that need to be reinstalled.

**Comment by nantille** [comment]
I reinstalled the whole IBL environment and numpy fails again. Since I cleaned my system from previous installs, rebooted and performed a full reinstall of this environment, it doesn't seem related to existing packages on my computer.

Here's the (lengthy) error straight from import `numpy as np`:
```
>>> import numpy as np
Traceback (most recent call last):
  File "/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/opt/anaconda3/envs/iblenv/bin/python"
  * The NumPy version is: "1.19.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /opt/anaconda3/envs/iblenv/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so
  Reason: image not found
```

As a side-note, when I run `conda env create -f ./iblenv/iblenv.yaml` I always get this warning:
```
/opt/anaconda3/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by nantille** [comment]
So it seems that the step mentioned earlier makes everything work. Thanks stackoverflow.
```
pip uninstall numpy
pip install numpy
```
