### ISSUE TITLE
[Usage question] - How to get the list of all session eids available via ONE

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#82]
**Describe the question you have**
I would like to get the list of all session eids via ONE. I tried running this command `eids = one.search()` but got an error (see below).
What would be the best command ?

**Is your question related to a specific product?**
ONE

**Additional context**
Error: 

```
eids = one.search()
100%|█████████▉| 26250/26277 [01:10<00:00, 371.53it/s]
Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-e93fcfdc72f7>", line 1, in <module>
    eids = one.search()
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/oneibl/one.py", line 581, in search
    eids = [s['url'] for s in tqdm.tqdm(ses)]  # flattens session info
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/oneibl/one.py", line 581, in <listcomp>
    eids = [s['url'] for s in tqdm.tqdm(ses)]  # flattens session info
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.7/site-packages/tqdm/std.py", line 1174, in __iter__
    for obj in iterable:
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/oneibl/webclient.py", line 52, in __iter__
    yield self.__getitem__(i)
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/oneibl/webclient.py", line 47, in __getitem__
    self._cache[i + offset] = res['results'][i]
IndexError: list assignment index out of range
```

**Comment by k1o0** [comment]
You could list all sessions by doing `one.alyx.rest('sessions', 'list')` but I strongly recommend against this.  It is incredibly inefficient and there are many stub sessions that are of no use to anyone.  I'm not sure what you are trying to achieve but narrowing your search at least somewhat with `one.search` is probably the way to go.

**Comment by k1o0** [comment]
It's been a week so I'm going to go ahead and close this issue.  Feel free to reopen if necessary.
