### ISSUE TITLE
[Bug report] - Bug when using python make_script.py -c command to cleanup example notebooks

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#88]
**Describe the bug**
The `make_script` command generates changes in several notebook, which needs to be cleaned up.
When running the command `python make_script.py -c`, an error is encountered (see below).

**To Reproduce**
Follow the steps in iblenv>docs https://github.com/int-brain-lab/iblenv/tree/docs/docs_gh_pages and use `python make_script.py -c`

**Expected behavior**
Running without error, cleaning notebooks.

**Additional context**
Error:

```
(iblenv) macbook-pro-de-gaelle:docs_gh_pages gaelle$ python make_script.py -c
2020-10-29 13:50:19.381 INFO   [make_script.py:53] Cleaning up notebooks
2020-10-29 13:50:19.382 INFO   [execute_notebooks.py:261] Cleaning up notebook dj_intro.ipynb in /Users/gaelle/Documents/Git/int-brain-lab/iblenv/docs_gh_pages/notebooks/dj_intro
2020-10-29 13:50:19.402 INFO   [execute_notebooks.py:261] Cleaning up notebook one_basics.ipynb in /Users/gaelle/Documents/Git/int-brain-lab/iblenv/docs_gh_pages/notebooks/one_basics
2020-10-29 13:50:19.417 INFO   [execute_notebooks.py:261] Cleaning up notebook one_advanced.ipynb in /Users/gaelle/Documents/Git/int-brain-lab/iblenv/docs_gh_pages/notebooks/one_advanced
2020-10-29 13:50:19.431 INFO   [execute_notebooks.py:261] Cleaning up notebook dj_basics.ipynb in /Users/gaelle/Documents/Git/int-brain-lab/iblenv/docs_gh_pages/notebooks/dj_basics
2020-10-29 13:50:19.465 INFO   [execute_notebooks.py:261] Cleaning up notebook one_intro.ipynb in /Users/gaelle/Documents/Git/int-brain-lab/iblenv/docs_gh_pages/notebooks/one_intro
Traceback (most recent call last):
 File "make_script.py", line 86, in <module>
  clean=args.cleanup, github=args.github, message=args.message)
 File "make_script.py", line 57, in make_documentation
  filename_pattern='docs')
 File "/Users/gaelle/Documents/Git/int-brain-lab/iblenv/docs_gh_pages/scripts/execute_notebooks.py", line 375, in process_notebooks
  full_path = NotebookConverter.py_to_ipynb(full_path)
 File "/Users/gaelle/Documents/Git/int-brain-lab/iblenv/docs_gh_pages/scripts/execute_notebooks.py", line 97, in py_to_ipynb
  example_nb = sph_nb.jupyter_notebook(blocks, gallery_config)
TypeError: jupyter_notebook() missing 1 required positional argument: 'target_dir'
```

**Comment by mayofaulkner** [comment]
Issue solved in the latest changes pushed to iblenv/docs. Due to updated package version of sphinx-gallery that required extra argument
