### ISSUE TITLE
[Bug report] - Cannot run my alyx server for testing (not urgent)

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#90]
**Describe the bug**
Error:

```
(base) macbook-pro-de-gaelle:~ gaelle$ conda activate alyxenv
(alyxenv) macbook-pro-de-gaelle:~ gaelle$ cd Documents/Git/int-brain-lab/alyx/
(alyxenv) macbook-pro-de-gaelle:alyx gaelle$ alyx/manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/logging/config.py", line 736, in configure_handler
    result = factory(**kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/logging/handlers.py", line 148, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/logging/handlers.py", line 55, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/var/log/alyx.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/logging/config.py", line 800, in dictConfig
    dictConfigClass(config).configure()
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/logging/config.py", line 571, in configure
    '%r' % name) from e
ValueError: Unable to configure handler 'file'
```

**To Reproduce**
Get on my machine, and launch the commands as above.
Using alyx > reports branch

**Expected behavior**
Connection to server.

**Desktop (please complete the following information):**
 - OS: Mac OS

**Additional context**
It used to work fine a few weeks ago.

**Comment by rossant** [comment]
try:

`sudo touch /var/log/alyx.log; sudo chmod 776 /var/log/alyx.log;`

**Comment by GaelleChapuis** [comment]
Thanks! Another error:
```

(alyxenv) macbook-pro-de-gaelle:alyx gaelle$ alyx/manage.py runserver
29/10 15:06:45 [INFO] {autoreload.py:598} Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "%DBUSER%"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
    self.check_migrations()
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/core/management/base.py", line 458, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 76, in applied_migrations
    if self.has_table():
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 260, in cursor
    return self._cursor()
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 236, in _cursor
    self.ensure_connection()
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/Users/gaelle/opt/anaconda3/envs/alyxenv/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "%DBUSER%"

```
(you're off, it can wait for next week no problem :) ! )

**Comment by rossant** [comment]
something went wrong with the automatic setup script of alyx, not sure what (especially given it was working before)
Remind me to have a closer look when I'm back :)
