### ISSUE TITLE
error opening probe in ephys alignment gui

### ISSUE THREAD

**Issue by cskrasniak** [int-brain-lab/iblenv#95]
I've only seen this for one session so far, but it is strange because the other probe for this session loaded fine and data for both probes are on flatiron. 

error:
```CSH_ZAD_021
probe01
2020-06-16
b9003c82-6178-47ed-9ff2-75087a49c2f7
2020-11-03 14:07:12.201 WARNING  [one.py:178] dataset _iblqc_ephysSpectralDensity.amps not found for session: b9003c82-6178-47ed-9ff2-75087a49c2f7
Traceback (most recent call last):
  File "ephys_atlas_gui.py", line 886, in data_button_pressed
    brain_atlas=self.loaddata.brain_atlas)
  File "/Users/ckrasnia/Desktop/Zador_Lab/IBL/int-brain-lab/ibllib-repo/ibllib/pipes/ephys_alignment.py", line 32, in __init__
    self.track_extent[-1] - 10 * 1e-6, 10 * 1e-6)
ValueError: arange: cannot compute length
Abort trap: 6```

**Comment by mayofaulkner** [comment]
Hi Chris, i've made a fix that catches this problem in this merge https://github.com/int-brain-lab/ibllib/commit/dc0ccbacdb01e89f498ea2b7c55cb17299d33484. If you pull the latest changes in develop ibllib it should work with this probe.
